// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::active_skill_type::ActiveSkill;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `active_skill`.
///
/// Obtain a handle from the [`ActiveSkillTableAccess::active_skill`] method on [`super::RemoteTables`],
/// like `ctx.db.active_skill()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_skill().on_insert(...)`.
pub struct ActiveSkillTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActiveSkill>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `active_skill`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActiveSkillTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActiveSkillTableHandle`], which mediates access to the table `active_skill`.
    fn active_skill(&self) -> ActiveSkillTableHandle<'_>;
}

impl ActiveSkillTableAccess for super::RemoteTables {
    fn active_skill(&self) -> ActiveSkillTableHandle<'_> {
        ActiveSkillTableHandle {
            imp: self.imp.get_table::<ActiveSkill>("active_skill"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActiveSkillInsertCallbackId(__sdk::CallbackId);
pub struct ActiveSkillDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActiveSkillTableHandle<'ctx> {
    type Row = ActiveSkill;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActiveSkill> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActiveSkillInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveSkillInsertCallbackId {
        ActiveSkillInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveSkillInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActiveSkillDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveSkillDeleteCallbackId {
        ActiveSkillDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveSkillDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ActiveSkillUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActiveSkillTableHandle<'ctx> {
    type UpdateCallbackId = ActiveSkillUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActiveSkillUpdateCallbackId {
        ActiveSkillUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActiveSkillUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `active_skill`,
/// which allows point queries on the field of the same name
/// via the [`ActiveSkillScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_skill().scheduled_id().find(...)`.
pub struct ActiveSkillScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ActiveSkill, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActiveSkillTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `active_skill`.
    pub fn scheduled_id(&self) -> ActiveSkillScheduledIdUnique<'ctx> {
        ActiveSkillScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActiveSkillScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ActiveSkill> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActiveSkill>("active_skill");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ActiveSkill>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActiveSkill>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ActiveSkill`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait active_skillQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ActiveSkill`.
    fn active_skill(&self) -> __sdk::__query_builder::Table<ActiveSkill>;
}

impl active_skillQueryTableAccess for __sdk::QueryTableAccessor {
    fn active_skill(&self) -> __sdk::__query_builder::Table<ActiveSkill> {
        __sdk::__query_builder::Table::new("active_skill")
    }
}
