// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AoeZone {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub owner: __sdk::Identity,
    pub skill_id: u64,
    pub center_x: f32,
    pub center_y: f32,
    pub center_z: f32,
    pub radius: f32,
    pub power: i32,
    pub knockback: f32,
    pub tick_interval_ms: u64,
    pub last_tick_at: u64,
    pub started_at: u64,
}

impl __sdk::InModule for AoeZone {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AoeZone`.
///
/// Provides typed access to columns for query building.
pub struct AoeZoneCols {
    pub scheduled_id: __sdk::__query_builder::Col<AoeZone, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<AoeZone, __sdk::ScheduleAt>,
    pub owner: __sdk::__query_builder::Col<AoeZone, __sdk::Identity>,
    pub skill_id: __sdk::__query_builder::Col<AoeZone, u64>,
    pub center_x: __sdk::__query_builder::Col<AoeZone, f32>,
    pub center_y: __sdk::__query_builder::Col<AoeZone, f32>,
    pub center_z: __sdk::__query_builder::Col<AoeZone, f32>,
    pub radius: __sdk::__query_builder::Col<AoeZone, f32>,
    pub power: __sdk::__query_builder::Col<AoeZone, i32>,
    pub knockback: __sdk::__query_builder::Col<AoeZone, f32>,
    pub tick_interval_ms: __sdk::__query_builder::Col<AoeZone, u64>,
    pub last_tick_at: __sdk::__query_builder::Col<AoeZone, u64>,
    pub started_at: __sdk::__query_builder::Col<AoeZone, u64>,
}

impl __sdk::__query_builder::HasCols for AoeZone {
    type Cols = AoeZoneCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AoeZoneCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            skill_id: __sdk::__query_builder::Col::new(table_name, "skill_id"),
            center_x: __sdk::__query_builder::Col::new(table_name, "center_x"),
            center_y: __sdk::__query_builder::Col::new(table_name, "center_y"),
            center_z: __sdk::__query_builder::Col::new(table_name, "center_z"),
            radius: __sdk::__query_builder::Col::new(table_name, "radius"),
            power: __sdk::__query_builder::Col::new(table_name, "power"),
            knockback: __sdk::__query_builder::Col::new(table_name, "knockback"),
            tick_interval_ms: __sdk::__query_builder::Col::new(table_name, "tick_interval_ms"),
            last_tick_at: __sdk::__query_builder::Col::new(table_name, "last_tick_at"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AoeZone`.
///
/// Provides typed access to indexed columns for query building.
pub struct AoeZoneIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<AoeZone, u64>,
}

impl __sdk::__query_builder::HasIxCols for AoeZone {
    type IxCols = AoeZoneIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AoeZoneIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AoeZone {}
