// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::position_type::Position;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChatMessage {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub sender: __sdk::Identity,
    pub sender_name: String,
    pub text: String,
    pub position: Position,
}

impl __sdk::InModule for ChatMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChatMessage`.
///
/// Provides typed access to columns for query building.
pub struct ChatMessageCols {
    pub scheduled_id: __sdk::__query_builder::Col<ChatMessage, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<ChatMessage, __sdk::ScheduleAt>,
    pub sender: __sdk::__query_builder::Col<ChatMessage, __sdk::Identity>,
    pub sender_name: __sdk::__query_builder::Col<ChatMessage, String>,
    pub text: __sdk::__query_builder::Col<ChatMessage, String>,
    pub position: __sdk::__query_builder::Col<ChatMessage, Position>,
}

impl __sdk::__query_builder::HasCols for ChatMessage {
    type Cols = ChatMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChatMessageCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            sender: __sdk::__query_builder::Col::new(table_name, "sender"),
            sender_name: __sdk::__query_builder::Col::new(table_name, "sender_name"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
        }
    }
}

/// Indexed column accessor struct for the table `ChatMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChatMessageIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<ChatMessage, u64>,
}

impl __sdk::__query_builder::HasIxCols for ChatMessage {
    type IxCols = ChatMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChatMessageIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChatMessage {}
