// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_rarity_type::ItemRarity;
use super::item_type_type::ItemType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ItemDef {
    pub id: u64,
    pub name: String,
    pub item_type: ItemType,
    pub rarity: ItemRarity,
    pub max_stack: i32,
}

impl __sdk::InModule for ItemDef {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ItemDef`.
///
/// Provides typed access to columns for query building.
pub struct ItemDefCols {
    pub id: __sdk::__query_builder::Col<ItemDef, u64>,
    pub name: __sdk::__query_builder::Col<ItemDef, String>,
    pub item_type: __sdk::__query_builder::Col<ItemDef, ItemType>,
    pub rarity: __sdk::__query_builder::Col<ItemDef, ItemRarity>,
    pub max_stack: __sdk::__query_builder::Col<ItemDef, i32>,
}

impl __sdk::__query_builder::HasCols for ItemDef {
    type Cols = ItemDefCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ItemDefCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            item_type: __sdk::__query_builder::Col::new(table_name, "item_type"),
            rarity: __sdk::__query_builder::Col::new(table_name, "rarity"),
            max_stack: __sdk::__query_builder::Col::new(table_name, "max_stack"),
        }
    }
}

/// Indexed column accessor struct for the table `ItemDef`.
///
/// Provides typed access to indexed columns for query building.
pub struct ItemDefIxCols {
    pub id: __sdk::__query_builder::IxCol<ItemDef, u64>,
}

impl __sdk::__query_builder::HasIxCols for ItemDef {
    type IxCols = ItemDefIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ItemDefIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ItemDef {}
