// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_emotion_type::NpcEmotion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_emotion`.
///
/// Obtain a handle from the [`NpcEmotionTableAccess::npc_emotion`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_emotion()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_emotion().on_insert(...)`.
pub struct NpcEmotionTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcEmotion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_emotion`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcEmotionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcEmotionTableHandle`], which mediates access to the table `npc_emotion`.
    fn npc_emotion(&self) -> NpcEmotionTableHandle<'_>;
}

impl NpcEmotionTableAccess for super::RemoteTables {
    fn npc_emotion(&self) -> NpcEmotionTableHandle<'_> {
        NpcEmotionTableHandle {
            imp: self.imp.get_table::<NpcEmotion>("npc_emotion"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcEmotionInsertCallbackId(__sdk::CallbackId);
pub struct NpcEmotionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcEmotionTableHandle<'ctx> {
    type Row = NpcEmotion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcEmotion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcEmotionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcEmotionInsertCallbackId {
        NpcEmotionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcEmotionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcEmotionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcEmotionDeleteCallbackId {
        NpcEmotionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcEmotionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcEmotionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcEmotionTableHandle<'ctx> {
    type UpdateCallbackId = NpcEmotionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcEmotionUpdateCallbackId {
        NpcEmotionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcEmotionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `npc_id` unique index on the table `npc_emotion`,
/// which allows point queries on the field of the same name
/// via the [`NpcEmotionNpcIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_emotion().npc_id().find(...)`.
pub struct NpcEmotionNpcIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcEmotion, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcEmotionTableHandle<'ctx> {
    /// Get a handle on the `npc_id` unique index on the table `npc_emotion`.
    pub fn npc_id(&self) -> NpcEmotionNpcIdUnique<'ctx> {
        NpcEmotionNpcIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("npc_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcEmotionNpcIdUnique<'ctx> {
    /// Find the subscribed row whose `npc_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcEmotion> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcEmotion>("npc_emotion");
    _table.add_unique_constraint::<u64>("npc_id", |row| &row.npc_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcEmotion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcEmotion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcEmotion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_emotionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcEmotion`.
    fn npc_emotion(&self) -> __sdk::__query_builder::Table<NpcEmotion>;
}

impl npc_emotionQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_emotion(&self) -> __sdk::__query_builder::Table<NpcEmotion> {
        __sdk::__query_builder::Table::new("npc_emotion")
    }
}
