// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::position_type::Position;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcChatMessage {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub npc_id: u64,
    pub text: String,
    pub position: Position,
}

impl __sdk::InModule for NpcChatMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcChatMessage`.
///
/// Provides typed access to columns for query building.
pub struct NpcChatMessageCols {
    pub scheduled_id: __sdk::__query_builder::Col<NpcChatMessage, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<NpcChatMessage, __sdk::ScheduleAt>,
    pub npc_id: __sdk::__query_builder::Col<NpcChatMessage, u64>,
    pub text: __sdk::__query_builder::Col<NpcChatMessage, String>,
    pub position: __sdk::__query_builder::Col<NpcChatMessage, Position>,
}

impl __sdk::__query_builder::HasCols for NpcChatMessage {
    type Cols = NpcChatMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcChatMessageCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcChatMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcChatMessageIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<NpcChatMessage, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcChatMessage {
    type IxCols = NpcChatMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcChatMessageIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcChatMessage {}
