// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerSkill {
    pub id: u64,
    pub player_identity: __sdk::Identity,
    pub skill_id: u64,
    pub level: i32,
    pub xp: i32,
}

impl __sdk::InModule for PlayerSkill {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerSkill`.
///
/// Provides typed access to columns for query building.
pub struct PlayerSkillCols {
    pub id: __sdk::__query_builder::Col<PlayerSkill, u64>,
    pub player_identity: __sdk::__query_builder::Col<PlayerSkill, __sdk::Identity>,
    pub skill_id: __sdk::__query_builder::Col<PlayerSkill, u64>,
    pub level: __sdk::__query_builder::Col<PlayerSkill, i32>,
    pub xp: __sdk::__query_builder::Col<PlayerSkill, i32>,
}

impl __sdk::__query_builder::HasCols for PlayerSkill {
    type Cols = PlayerSkillCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerSkillCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            player_identity: __sdk::__query_builder::Col::new(table_name, "player_identity"),
            skill_id: __sdk::__query_builder::Col::new(table_name, "skill_id"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            xp: __sdk::__query_builder::Col::new(table_name, "xp"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerSkill`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerSkillIxCols {
    pub id: __sdk::__query_builder::IxCol<PlayerSkill, u64>,
}

impl __sdk::__query_builder::HasIxCols for PlayerSkill {
    type IxCols = PlayerSkillIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerSkillIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PlayerSkill {}
