// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeCapture {
    pub lease_id: u64,
    pub run: String,
    pub actor: u32,
    pub observation: String,
}

impl __sdk::InModule for SimNativeCapture {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeCapture`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeCaptureCols {
    pub lease_id: __sdk::__query_builder::Col<SimNativeCapture, u64>,
    pub run: __sdk::__query_builder::Col<SimNativeCapture, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeCapture, u32>,
    pub observation: __sdk::__query_builder::Col<SimNativeCapture, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeCapture {
    type Cols = SimNativeCaptureCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeCaptureCols {
            lease_id: __sdk::__query_builder::Col::new(table_name, "lease_id"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            observation: __sdk::__query_builder::Col::new(table_name, "observation"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeCapture`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeCaptureIxCols {
    pub lease_id: __sdk::__query_builder::IxCol<SimNativeCapture, u64>,
    pub run: __sdk::__query_builder::IxCol<SimNativeCapture, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeCapture {
    type IxCols = SimNativeCaptureIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeCaptureIxCols {
            lease_id: __sdk::__query_builder::IxCol::new(table_name, "lease_id"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeCapture {}
