// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_client_snapshot_type::SimClientSnapshot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_snapshot`.
///
/// Obtain a handle from the [`SimMySnapshotTableAccess::sim_my_snapshot`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_snapshot()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_snapshot().on_insert(...)`.
pub struct SimMySnapshotTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimClientSnapshot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_snapshot`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMySnapshotTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMySnapshotTableHandle`], which mediates access to the table `sim_my_snapshot`.
    fn sim_my_snapshot(&self) -> SimMySnapshotTableHandle<'_>;
}

impl SimMySnapshotTableAccess for super::RemoteTables {
    fn sim_my_snapshot(&self) -> SimMySnapshotTableHandle<'_> {
        SimMySnapshotTableHandle {
            imp: self.imp.get_table::<SimClientSnapshot>("sim_my_snapshot"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMySnapshotInsertCallbackId(__sdk::CallbackId);
pub struct SimMySnapshotDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMySnapshotTableHandle<'ctx> {
    type Row = SimClientSnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimClientSnapshot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMySnapshotInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMySnapshotInsertCallbackId {
        SimMySnapshotInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMySnapshotInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMySnapshotDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMySnapshotDeleteCallbackId {
        SimMySnapshotDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMySnapshotDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimClientSnapshot>("sim_my_snapshot");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimClientSnapshot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimClientSnapshot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimClientSnapshot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_snapshotQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimClientSnapshot`.
    fn sim_my_snapshot(&self) -> __sdk::__query_builder::Table<SimClientSnapshot>;
}

impl sim_my_snapshotQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_snapshot(&self) -> __sdk::__query_builder::Table<SimClientSnapshot> {
        __sdk::__query_builder::Table::new("sim_my_snapshot")
    }
}
