// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeStation {
    pub key: String,
    pub run: String,
    pub station: u32,
    pub ordinal: u32,
    pub position: i32,
    pub owner: u32,
    pub label: String,
    pub electricity: i32,
    pub electricity_capacity: i32,
    pub parts: i32,
    pub water: i32,
    pub modules: String,
    pub access: String,
    pub generation_period_ms: u64,
    pub generation_amount: i32,
    pub enabled: bool,
    pub integrity: i32,
    pub embodied_parts: i32,
    pub repair_parts_consumed: i32,
    pub generation_remainder_ms: u64,
    pub compute_remainder_ms: u64,
    pub jobs: String,
}

impl __sdk::InModule for SimNativeStation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeStation`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeStationCols {
    pub key: __sdk::__query_builder::Col<SimNativeStation, String>,
    pub run: __sdk::__query_builder::Col<SimNativeStation, String>,
    pub station: __sdk::__query_builder::Col<SimNativeStation, u32>,
    pub ordinal: __sdk::__query_builder::Col<SimNativeStation, u32>,
    pub position: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub owner: __sdk::__query_builder::Col<SimNativeStation, u32>,
    pub label: __sdk::__query_builder::Col<SimNativeStation, String>,
    pub electricity: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub electricity_capacity: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub parts: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub water: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub modules: __sdk::__query_builder::Col<SimNativeStation, String>,
    pub access: __sdk::__query_builder::Col<SimNativeStation, String>,
    pub generation_period_ms: __sdk::__query_builder::Col<SimNativeStation, u64>,
    pub generation_amount: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub enabled: __sdk::__query_builder::Col<SimNativeStation, bool>,
    pub integrity: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub embodied_parts: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub repair_parts_consumed: __sdk::__query_builder::Col<SimNativeStation, i32>,
    pub generation_remainder_ms: __sdk::__query_builder::Col<SimNativeStation, u64>,
    pub compute_remainder_ms: __sdk::__query_builder::Col<SimNativeStation, u64>,
    pub jobs: __sdk::__query_builder::Col<SimNativeStation, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeStation {
    type Cols = SimNativeStationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeStationCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            station: __sdk::__query_builder::Col::new(table_name, "station"),
            ordinal: __sdk::__query_builder::Col::new(table_name, "ordinal"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            label: __sdk::__query_builder::Col::new(table_name, "label"),
            electricity: __sdk::__query_builder::Col::new(table_name, "electricity"),
            electricity_capacity: __sdk::__query_builder::Col::new(
                table_name,
                "electricity_capacity",
            ),
            parts: __sdk::__query_builder::Col::new(table_name, "parts"),
            water: __sdk::__query_builder::Col::new(table_name, "water"),
            modules: __sdk::__query_builder::Col::new(table_name, "modules"),
            access: __sdk::__query_builder::Col::new(table_name, "access"),
            generation_period_ms: __sdk::__query_builder::Col::new(
                table_name,
                "generation_period_ms",
            ),
            generation_amount: __sdk::__query_builder::Col::new(table_name, "generation_amount"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
            integrity: __sdk::__query_builder::Col::new(table_name, "integrity"),
            embodied_parts: __sdk::__query_builder::Col::new(table_name, "embodied_parts"),
            repair_parts_consumed: __sdk::__query_builder::Col::new(
                table_name,
                "repair_parts_consumed",
            ),
            generation_remainder_ms: __sdk::__query_builder::Col::new(
                table_name,
                "generation_remainder_ms",
            ),
            compute_remainder_ms: __sdk::__query_builder::Col::new(
                table_name,
                "compute_remainder_ms",
            ),
            jobs: __sdk::__query_builder::Col::new(table_name, "jobs"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeStation`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeStationIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeStation, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeStation, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeStation {
    type IxCols = SimNativeStationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeStationIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeStation {}
