// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::skill_attributes_type::SkillAttributes;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `skill_attributes`.
///
/// Obtain a handle from the [`SkillAttributesTableAccess::skill_attributes`] method on [`super::RemoteTables`],
/// like `ctx.db.skill_attributes()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_attributes().on_insert(...)`.
pub struct SkillAttributesTableHandle<'ctx> {
    imp: __sdk::TableHandle<SkillAttributes>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `skill_attributes`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SkillAttributesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SkillAttributesTableHandle`], which mediates access to the table `skill_attributes`.
    fn skill_attributes(&self) -> SkillAttributesTableHandle<'_>;
}

impl SkillAttributesTableAccess for super::RemoteTables {
    fn skill_attributes(&self) -> SkillAttributesTableHandle<'_> {
        SkillAttributesTableHandle {
            imp: self.imp.get_table::<SkillAttributes>("skill_attributes"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SkillAttributesInsertCallbackId(__sdk::CallbackId);
pub struct SkillAttributesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SkillAttributesTableHandle<'ctx> {
    type Row = SkillAttributes;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SkillAttributes> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SkillAttributesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillAttributesInsertCallbackId {
        SkillAttributesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillAttributesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SkillAttributesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillAttributesDeleteCallbackId {
        SkillAttributesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillAttributesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SkillAttributesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SkillAttributesTableHandle<'ctx> {
    type UpdateCallbackId = SkillAttributesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillAttributesUpdateCallbackId {
        SkillAttributesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillAttributesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `skill_attributes`,
/// which allows point queries on the field of the same name
/// via the [`SkillAttributesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_attributes().id().find(...)`.
pub struct SkillAttributesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SkillAttributes, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SkillAttributesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `skill_attributes`.
    pub fn id(&self) -> SkillAttributesIdUnique<'ctx> {
        SkillAttributesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SkillAttributesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SkillAttributes> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SkillAttributes>("skill_attributes");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SkillAttributes>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SkillAttributes>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SkillAttributes`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait skill_attributesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SkillAttributes`.
    fn skill_attributes(&self) -> __sdk::__query_builder::Table<SkillAttributes>;
}

impl skill_attributesQueryTableAccess for __sdk::QueryTableAccessor {
    fn skill_attributes(&self) -> __sdk::__query_builder::Table<SkillAttributes> {
        __sdk::__query_builder::Table::new("skill_attributes")
    }
}
