// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DropItemArgs {
    pub inventory_item_id: u64,
}

impl From<DropItemArgs> for super::Reducer {
    fn from(args: DropItemArgs) -> Self {
        Self::DropItem {
            inventory_item_id: args.inventory_item_id,
        }
    }
}

impl __sdk::InModule for DropItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `drop_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait drop_item {
    /// Request that the remote module invoke the reducer `drop_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`drop_item:drop_item_then`] to run a callback after the reducer completes.
    fn drop_item(&self, inventory_item_id: u64) -> __sdk::Result<()> {
        self.drop_item_then(inventory_item_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `drop_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn drop_item_then(
        &self,
        inventory_item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl drop_item for super::RemoteReducers {
    fn drop_item_then(
        &self,
        inventory_item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DropItemArgs { inventory_item_id }, callback)
    }
}
