// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::equip_slot_type::EquipSlot;
use super::equipped_item_type::EquippedItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `equipped_item`.
///
/// Obtain a handle from the [`EquippedItemTableAccess::equipped_item`] method on [`super::RemoteTables`],
/// like `ctx.db.equipped_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.equipped_item().on_insert(...)`.
pub struct EquippedItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<EquippedItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `equipped_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EquippedItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EquippedItemTableHandle`], which mediates access to the table `equipped_item`.
    fn equipped_item(&self) -> EquippedItemTableHandle<'_>;
}

impl EquippedItemTableAccess for super::RemoteTables {
    fn equipped_item(&self) -> EquippedItemTableHandle<'_> {
        EquippedItemTableHandle {
            imp: self.imp.get_table::<EquippedItem>("equipped_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EquippedItemInsertCallbackId(__sdk::CallbackId);
pub struct EquippedItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EquippedItemTableHandle<'ctx> {
    type Row = EquippedItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EquippedItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EquippedItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EquippedItemInsertCallbackId {
        EquippedItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EquippedItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EquippedItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EquippedItemDeleteCallbackId {
        EquippedItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EquippedItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EquippedItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EquippedItemTableHandle<'ctx> {
    type UpdateCallbackId = EquippedItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EquippedItemUpdateCallbackId {
        EquippedItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EquippedItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `equipped_item`,
/// which allows point queries on the field of the same name
/// via the [`EquippedItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.equipped_item().id().find(...)`.
pub struct EquippedItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EquippedItem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EquippedItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `equipped_item`.
    pub fn id(&self) -> EquippedItemIdUnique<'ctx> {
        EquippedItemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EquippedItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EquippedItem> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EquippedItem>("equipped_item");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EquippedItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EquippedItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EquippedItem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait equipped_itemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EquippedItem`.
    fn equipped_item(&self) -> __sdk::__query_builder::Table<EquippedItem>;
}

impl equipped_itemQueryTableAccess for __sdk::QueryTableAccessor {
    fn equipped_item(&self) -> __sdk::__query_builder::Table<EquippedItem> {
        __sdk::__query_builder::Table::new("equipped_item")
    }
}
