// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InventoryItem {
    pub id: u64,
    pub player_identity: __sdk::Identity,
    pub slot: i32,
    pub item_def_id: u64,
    pub quantity: i32,
}

impl __sdk::InModule for InventoryItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InventoryItem`.
///
/// Provides typed access to columns for query building.
pub struct InventoryItemCols {
    pub id: __sdk::__query_builder::Col<InventoryItem, u64>,
    pub player_identity: __sdk::__query_builder::Col<InventoryItem, __sdk::Identity>,
    pub slot: __sdk::__query_builder::Col<InventoryItem, i32>,
    pub item_def_id: __sdk::__query_builder::Col<InventoryItem, u64>,
    pub quantity: __sdk::__query_builder::Col<InventoryItem, i32>,
}

impl __sdk::__query_builder::HasCols for InventoryItem {
    type Cols = InventoryItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InventoryItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            player_identity: __sdk::__query_builder::Col::new(table_name, "player_identity"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
            item_def_id: __sdk::__query_builder::Col::new(table_name, "item_def_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
        }
    }
}

/// Indexed column accessor struct for the table `InventoryItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct InventoryItemIxCols {
    pub id: __sdk::__query_builder::IxCol<InventoryItem, u64>,
}

impl __sdk::__query_builder::HasIxCols for InventoryItem {
    type IxCols = InventoryItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InventoryItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InventoryItem {}
