// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::loot_table_entry_type::LootTableEntry;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `loot_table_entry`.
///
/// Obtain a handle from the [`LootTableEntryTableAccess::loot_table_entry`] method on [`super::RemoteTables`],
/// like `ctx.db.loot_table_entry()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loot_table_entry().on_insert(...)`.
pub struct LootTableEntryTableHandle<'ctx> {
    imp: __sdk::TableHandle<LootTableEntry>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `loot_table_entry`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LootTableEntryTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LootTableEntryTableHandle`], which mediates access to the table `loot_table_entry`.
    fn loot_table_entry(&self) -> LootTableEntryTableHandle<'_>;
}

impl LootTableEntryTableAccess for super::RemoteTables {
    fn loot_table_entry(&self) -> LootTableEntryTableHandle<'_> {
        LootTableEntryTableHandle {
            imp: self.imp.get_table::<LootTableEntry>("loot_table_entry"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LootTableEntryInsertCallbackId(__sdk::CallbackId);
pub struct LootTableEntryDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LootTableEntryTableHandle<'ctx> {
    type Row = LootTableEntry;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LootTableEntry> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LootTableEntryInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootTableEntryInsertCallbackId {
        LootTableEntryInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LootTableEntryInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LootTableEntryDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LootTableEntryDeleteCallbackId {
        LootTableEntryDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LootTableEntryDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct LootTableEntryUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for LootTableEntryTableHandle<'ctx> {
    type UpdateCallbackId = LootTableEntryUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> LootTableEntryUpdateCallbackId {
        LootTableEntryUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: LootTableEntryUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `loot_table_entry`,
/// which allows point queries on the field of the same name
/// via the [`LootTableEntryIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.loot_table_entry().id().find(...)`.
pub struct LootTableEntryIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<LootTableEntry, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> LootTableEntryTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `loot_table_entry`.
    pub fn id(&self) -> LootTableEntryIdUnique<'ctx> {
        LootTableEntryIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> LootTableEntryIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<LootTableEntry> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LootTableEntry>("loot_table_entry");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LootTableEntry>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LootTableEntry>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LootTableEntry`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait loot_table_entryQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LootTableEntry`.
    fn loot_table_entry(&self) -> __sdk::__query_builder::Table<LootTableEntry>;
}

impl loot_table_entryQueryTableAccess for __sdk::QueryTableAccessor {
    fn loot_table_entry(&self) -> __sdk::__query_builder::Table<LootTableEntry> {
        __sdk::__query_builder::Table::new("loot_table_entry")
    }
}
