// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcPendingDecision {
    pub npc_id: u64,
    pub context: String,
}

impl __sdk::InModule for NpcPendingDecision {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcPendingDecision`.
///
/// Provides typed access to columns for query building.
pub struct NpcPendingDecisionCols {
    pub npc_id: __sdk::__query_builder::Col<NpcPendingDecision, u64>,
    pub context: __sdk::__query_builder::Col<NpcPendingDecision, String>,
}

impl __sdk::__query_builder::HasCols for NpcPendingDecision {
    type Cols = NpcPendingDecisionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcPendingDecisionCols {
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            context: __sdk::__query_builder::Col::new(table_name, "context"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcPendingDecision`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcPendingDecisionIxCols {
    pub npc_id: __sdk::__query_builder::IxCol<NpcPendingDecision, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcPendingDecision {
    type IxCols = NpcPendingDecisionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcPendingDecisionIxCols {
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcPendingDecision {}
