// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_behaviour_graph_type::NpcBehaviourGraph;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_behaviour_graph`.
///
/// Obtain a handle from the [`NpcBehaviourGraphTableAccess::npc_behaviour_graph`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_behaviour_graph()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_behaviour_graph().on_insert(...)`.
pub struct NpcBehaviourGraphTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcBehaviourGraph>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_behaviour_graph`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcBehaviourGraphTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcBehaviourGraphTableHandle`], which mediates access to the table `npc_behaviour_graph`.
    fn npc_behaviour_graph(&self) -> NpcBehaviourGraphTableHandle<'_>;
}

impl NpcBehaviourGraphTableAccess for super::RemoteTables {
    fn npc_behaviour_graph(&self) -> NpcBehaviourGraphTableHandle<'_> {
        NpcBehaviourGraphTableHandle {
            imp: self
                .imp
                .get_table::<NpcBehaviourGraph>("npc_behaviour_graph"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcBehaviourGraphInsertCallbackId(__sdk::CallbackId);
pub struct NpcBehaviourGraphDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcBehaviourGraphTableHandle<'ctx> {
    type Row = NpcBehaviourGraph;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcBehaviourGraph> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcBehaviourGraphInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBehaviourGraphInsertCallbackId {
        NpcBehaviourGraphInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcBehaviourGraphInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcBehaviourGraphDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcBehaviourGraphDeleteCallbackId {
        NpcBehaviourGraphDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcBehaviourGraphDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcBehaviourGraphUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcBehaviourGraphTableHandle<'ctx> {
    type UpdateCallbackId = NpcBehaviourGraphUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcBehaviourGraphUpdateCallbackId {
        NpcBehaviourGraphUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcBehaviourGraphUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `npc_id` unique index on the table `npc_behaviour_graph`,
/// which allows point queries on the field of the same name
/// via the [`NpcBehaviourGraphNpcIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_behaviour_graph().npc_id().find(...)`.
pub struct NpcBehaviourGraphNpcIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcBehaviourGraph, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcBehaviourGraphTableHandle<'ctx> {
    /// Get a handle on the `npc_id` unique index on the table `npc_behaviour_graph`.
    pub fn npc_id(&self) -> NpcBehaviourGraphNpcIdUnique<'ctx> {
        NpcBehaviourGraphNpcIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("npc_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcBehaviourGraphNpcIdUnique<'ctx> {
    /// Find the subscribed row whose `npc_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcBehaviourGraph> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcBehaviourGraph>("npc_behaviour_graph");
    _table.add_unique_constraint::<u64>("npc_id", |row| &row.npc_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcBehaviourGraph>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcBehaviourGraph>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcBehaviourGraph`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_behaviour_graphQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcBehaviourGraph`.
    fn npc_behaviour_graph(&self) -> __sdk::__query_builder::Table<NpcBehaviourGraph>;
}

impl npc_behaviour_graphQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_behaviour_graph(&self) -> __sdk::__query_builder::Table<NpcBehaviourGraph> {
        __sdk::__query_builder::Table::new("npc_behaviour_graph")
    }
}
