// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcBehavior {
    pub npc_id: u64,
    pub mode: String,
    pub combat_tree: String,
}

impl __sdk::InModule for NpcBehavior {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcBehavior`.
///
/// Provides typed access to columns for query building.
pub struct NpcBehaviorCols {
    pub npc_id: __sdk::__query_builder::Col<NpcBehavior, u64>,
    pub mode: __sdk::__query_builder::Col<NpcBehavior, String>,
    pub combat_tree: __sdk::__query_builder::Col<NpcBehavior, String>,
}

impl __sdk::__query_builder::HasCols for NpcBehavior {
    type Cols = NpcBehaviorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcBehaviorCols {
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            combat_tree: __sdk::__query_builder::Col::new(table_name, "combat_tree"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcBehavior`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcBehaviorIxCols {
    pub npc_id: __sdk::__query_builder::IxCol<NpcBehavior, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcBehavior {
    type IxCols = NpcBehaviorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcBehaviorIxCols {
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcBehavior {}
