// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcPlan {
    pub npc_id: u64,
    pub steps: String,
    pub current_step: i32,
}

impl __sdk::InModule for NpcPlan {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcPlan`.
///
/// Provides typed access to columns for query building.
pub struct NpcPlanCols {
    pub npc_id: __sdk::__query_builder::Col<NpcPlan, u64>,
    pub steps: __sdk::__query_builder::Col<NpcPlan, String>,
    pub current_step: __sdk::__query_builder::Col<NpcPlan, i32>,
}

impl __sdk::__query_builder::HasCols for NpcPlan {
    type Cols = NpcPlanCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcPlanCols {
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            steps: __sdk::__query_builder::Col::new(table_name, "steps"),
            current_step: __sdk::__query_builder::Col::new(table_name, "current_step"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcPlan`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcPlanIxCols {
    pub npc_id: __sdk::__query_builder::IxCol<NpcPlan, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcPlan {
    type IxCols = NpcPlanIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcPlanIxCols {
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcPlan {}
