// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::goal_priority_type::GoalPriority;
use super::goal_status_type::GoalStatus;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcGoal {
    pub id: u64,
    pub npc_id: u64,
    pub parent_goal_id: u64,
    pub priority: GoalPriority,
    pub status: GoalStatus,
    pub description: String,
    pub success_condition: String,
    pub created_at: u64,
    pub completed_at: u64,
}

impl __sdk::InModule for NpcGoal {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcGoal`.
///
/// Provides typed access to columns for query building.
pub struct NpcGoalCols {
    pub id: __sdk::__query_builder::Col<NpcGoal, u64>,
    pub npc_id: __sdk::__query_builder::Col<NpcGoal, u64>,
    pub parent_goal_id: __sdk::__query_builder::Col<NpcGoal, u64>,
    pub priority: __sdk::__query_builder::Col<NpcGoal, GoalPriority>,
    pub status: __sdk::__query_builder::Col<NpcGoal, GoalStatus>,
    pub description: __sdk::__query_builder::Col<NpcGoal, String>,
    pub success_condition: __sdk::__query_builder::Col<NpcGoal, String>,
    pub created_at: __sdk::__query_builder::Col<NpcGoal, u64>,
    pub completed_at: __sdk::__query_builder::Col<NpcGoal, u64>,
}

impl __sdk::__query_builder::HasCols for NpcGoal {
    type Cols = NpcGoalCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcGoalCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            parent_goal_id: __sdk::__query_builder::Col::new(table_name, "parent_goal_id"),
            priority: __sdk::__query_builder::Col::new(table_name, "priority"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            success_condition: __sdk::__query_builder::Col::new(table_name, "success_condition"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            completed_at: __sdk::__query_builder::Col::new(table_name, "completed_at"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcGoal`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcGoalIxCols {
    pub id: __sdk::__query_builder::IxCol<NpcGoal, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcGoal {
    type IxCols = NpcGoalIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcGoalIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcGoal {}
