// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_relationship_type::NpcRelationship;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_relationship`.
///
/// Obtain a handle from the [`NpcRelationshipTableAccess::npc_relationship`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_relationship()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_relationship().on_insert(...)`.
pub struct NpcRelationshipTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcRelationship>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_relationship`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcRelationshipTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcRelationshipTableHandle`], which mediates access to the table `npc_relationship`.
    fn npc_relationship(&self) -> NpcRelationshipTableHandle<'_>;
}

impl NpcRelationshipTableAccess for super::RemoteTables {
    fn npc_relationship(&self) -> NpcRelationshipTableHandle<'_> {
        NpcRelationshipTableHandle {
            imp: self.imp.get_table::<NpcRelationship>("npc_relationship"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcRelationshipInsertCallbackId(__sdk::CallbackId);
pub struct NpcRelationshipDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcRelationshipTableHandle<'ctx> {
    type Row = NpcRelationship;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcRelationship> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcRelationshipInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcRelationshipInsertCallbackId {
        NpcRelationshipInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcRelationshipInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcRelationshipDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcRelationshipDeleteCallbackId {
        NpcRelationshipDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcRelationshipDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcRelationshipUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcRelationshipTableHandle<'ctx> {
    type UpdateCallbackId = NpcRelationshipUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcRelationshipUpdateCallbackId {
        NpcRelationshipUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcRelationshipUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `npc_relationship`,
/// which allows point queries on the field of the same name
/// via the [`NpcRelationshipIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_relationship().id().find(...)`.
pub struct NpcRelationshipIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcRelationship, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcRelationshipTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `npc_relationship`.
    pub fn id(&self) -> NpcRelationshipIdUnique<'ctx> {
        NpcRelationshipIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcRelationshipIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcRelationship> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcRelationship>("npc_relationship");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcRelationship>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcRelationship>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcRelationship`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_relationshipQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcRelationship`.
    fn npc_relationship(&self) -> __sdk::__query_builder::Table<NpcRelationship>;
}

impl npc_relationshipQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_relationship(&self) -> __sdk::__query_builder::Table<NpcRelationship> {
        __sdk::__query_builder::Table::new("npc_relationship")
    }
}
