// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_personality_type::NpcPersonality;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_personality`.
///
/// Obtain a handle from the [`NpcPersonalityTableAccess::npc_personality`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_personality()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_personality().on_insert(...)`.
pub struct NpcPersonalityTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcPersonality>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_personality`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcPersonalityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcPersonalityTableHandle`], which mediates access to the table `npc_personality`.
    fn npc_personality(&self) -> NpcPersonalityTableHandle<'_>;
}

impl NpcPersonalityTableAccess for super::RemoteTables {
    fn npc_personality(&self) -> NpcPersonalityTableHandle<'_> {
        NpcPersonalityTableHandle {
            imp: self.imp.get_table::<NpcPersonality>("npc_personality"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcPersonalityInsertCallbackId(__sdk::CallbackId);
pub struct NpcPersonalityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcPersonalityTableHandle<'ctx> {
    type Row = NpcPersonality;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcPersonality> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcPersonalityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcPersonalityInsertCallbackId {
        NpcPersonalityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcPersonalityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcPersonalityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcPersonalityDeleteCallbackId {
        NpcPersonalityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcPersonalityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcPersonalityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcPersonalityTableHandle<'ctx> {
    type UpdateCallbackId = NpcPersonalityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcPersonalityUpdateCallbackId {
        NpcPersonalityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcPersonalityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `npc_id` unique index on the table `npc_personality`,
/// which allows point queries on the field of the same name
/// via the [`NpcPersonalityNpcIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_personality().npc_id().find(...)`.
pub struct NpcPersonalityNpcIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcPersonality, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcPersonalityTableHandle<'ctx> {
    /// Get a handle on the `npc_id` unique index on the table `npc_personality`.
    pub fn npc_id(&self) -> NpcPersonalityNpcIdUnique<'ctx> {
        NpcPersonalityNpcIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("npc_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcPersonalityNpcIdUnique<'ctx> {
    /// Find the subscribed row whose `npc_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcPersonality> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcPersonality>("npc_personality");
    _table.add_unique_constraint::<u64>("npc_id", |row| &row.npc_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcPersonality>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcPersonality>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcPersonality`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_personalityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcPersonality`.
    fn npc_personality(&self) -> __sdk::__query_builder::Table<NpcPersonality>;
}

impl npc_personalityQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_personality(&self) -> __sdk::__query_builder::Table<NpcPersonality> {
        __sdk::__query_builder::Table::new("npc_personality")
    }
}
