// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcPersonality {
    pub npc_id: u64,
    pub aggression: f32,
    pub sociability: f32,
    pub curiosity: f32,
    pub courage: f32,
    pub empathy: f32,
    pub discipline: f32,
}

impl __sdk::InModule for NpcPersonality {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcPersonality`.
///
/// Provides typed access to columns for query building.
pub struct NpcPersonalityCols {
    pub npc_id: __sdk::__query_builder::Col<NpcPersonality, u64>,
    pub aggression: __sdk::__query_builder::Col<NpcPersonality, f32>,
    pub sociability: __sdk::__query_builder::Col<NpcPersonality, f32>,
    pub curiosity: __sdk::__query_builder::Col<NpcPersonality, f32>,
    pub courage: __sdk::__query_builder::Col<NpcPersonality, f32>,
    pub empathy: __sdk::__query_builder::Col<NpcPersonality, f32>,
    pub discipline: __sdk::__query_builder::Col<NpcPersonality, f32>,
}

impl __sdk::__query_builder::HasCols for NpcPersonality {
    type Cols = NpcPersonalityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcPersonalityCols {
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            aggression: __sdk::__query_builder::Col::new(table_name, "aggression"),
            sociability: __sdk::__query_builder::Col::new(table_name, "sociability"),
            curiosity: __sdk::__query_builder::Col::new(table_name, "curiosity"),
            courage: __sdk::__query_builder::Col::new(table_name, "courage"),
            empathy: __sdk::__query_builder::Col::new(table_name, "empathy"),
            discipline: __sdk::__query_builder::Col::new(table_name, "discipline"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcPersonality`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcPersonalityIxCols {
    pub npc_id: __sdk::__query_builder::IxCol<NpcPersonality, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcPersonality {
    type IxCols = NpcPersonalityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcPersonalityIxCols {
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcPersonality {}
