// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcEmotion {
    pub npc_id: u64,
    pub anger: f32,
    pub fear: f32,
    pub joy: f32,
    pub sadness: f32,
    pub surprise: f32,
    pub disgust: f32,
}

impl __sdk::InModule for NpcEmotion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcEmotion`.
///
/// Provides typed access to columns for query building.
pub struct NpcEmotionCols {
    pub npc_id: __sdk::__query_builder::Col<NpcEmotion, u64>,
    pub anger: __sdk::__query_builder::Col<NpcEmotion, f32>,
    pub fear: __sdk::__query_builder::Col<NpcEmotion, f32>,
    pub joy: __sdk::__query_builder::Col<NpcEmotion, f32>,
    pub sadness: __sdk::__query_builder::Col<NpcEmotion, f32>,
    pub surprise: __sdk::__query_builder::Col<NpcEmotion, f32>,
    pub disgust: __sdk::__query_builder::Col<NpcEmotion, f32>,
}

impl __sdk::__query_builder::HasCols for NpcEmotion {
    type Cols = NpcEmotionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcEmotionCols {
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            anger: __sdk::__query_builder::Col::new(table_name, "anger"),
            fear: __sdk::__query_builder::Col::new(table_name, "fear"),
            joy: __sdk::__query_builder::Col::new(table_name, "joy"),
            sadness: __sdk::__query_builder::Col::new(table_name, "sadness"),
            surprise: __sdk::__query_builder::Col::new(table_name, "surprise"),
            disgust: __sdk::__query_builder::Col::new(table_name, "disgust"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcEmotion`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcEmotionIxCols {
    pub npc_id: __sdk::__query_builder::IxCol<NpcEmotion, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcEmotion {
    type IxCols = NpcEmotionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcEmotionIxCols {
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcEmotion {}
