// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_knowledge_type::NpcKnowledge;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_knowledge`.
///
/// Obtain a handle from the [`NpcKnowledgeTableAccess::npc_knowledge`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_knowledge()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_knowledge().on_insert(...)`.
pub struct NpcKnowledgeTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcKnowledge>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_knowledge`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcKnowledgeTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcKnowledgeTableHandle`], which mediates access to the table `npc_knowledge`.
    fn npc_knowledge(&self) -> NpcKnowledgeTableHandle<'_>;
}

impl NpcKnowledgeTableAccess for super::RemoteTables {
    fn npc_knowledge(&self) -> NpcKnowledgeTableHandle<'_> {
        NpcKnowledgeTableHandle {
            imp: self.imp.get_table::<NpcKnowledge>("npc_knowledge"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcKnowledgeInsertCallbackId(__sdk::CallbackId);
pub struct NpcKnowledgeDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcKnowledgeTableHandle<'ctx> {
    type Row = NpcKnowledge;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcKnowledge> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcKnowledgeInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcKnowledgeInsertCallbackId {
        NpcKnowledgeInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcKnowledgeInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcKnowledgeDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcKnowledgeDeleteCallbackId {
        NpcKnowledgeDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcKnowledgeDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcKnowledgeUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcKnowledgeTableHandle<'ctx> {
    type UpdateCallbackId = NpcKnowledgeUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcKnowledgeUpdateCallbackId {
        NpcKnowledgeUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcKnowledgeUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `npc_knowledge`,
/// which allows point queries on the field of the same name
/// via the [`NpcKnowledgeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_knowledge().id().find(...)`.
pub struct NpcKnowledgeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcKnowledge, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcKnowledgeTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `npc_knowledge`.
    pub fn id(&self) -> NpcKnowledgeIdUnique<'ctx> {
        NpcKnowledgeIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcKnowledgeIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcKnowledge> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcKnowledge>("npc_knowledge");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcKnowledge>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcKnowledge>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcKnowledge`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_knowledgeQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcKnowledge`.
    fn npc_knowledge(&self) -> __sdk::__query_builder::Table<NpcKnowledge>;
}

impl npc_knowledgeQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_knowledge(&self) -> __sdk::__query_builder::Table<NpcKnowledge> {
        __sdk::__query_builder::Table::new("npc_knowledge")
    }
}
