// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::npc_inventory_item_type::NpcInventoryItem;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `npc_inventory_item`.
///
/// Obtain a handle from the [`NpcInventoryItemTableAccess::npc_inventory_item`] method on [`super::RemoteTables`],
/// like `ctx.db.npc_inventory_item()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_inventory_item().on_insert(...)`.
pub struct NpcInventoryItemTableHandle<'ctx> {
    imp: __sdk::TableHandle<NpcInventoryItem>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `npc_inventory_item`.
///
/// Implemented for [`super::RemoteTables`].
pub trait NpcInventoryItemTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`NpcInventoryItemTableHandle`], which mediates access to the table `npc_inventory_item`.
    fn npc_inventory_item(&self) -> NpcInventoryItemTableHandle<'_>;
}

impl NpcInventoryItemTableAccess for super::RemoteTables {
    fn npc_inventory_item(&self) -> NpcInventoryItemTableHandle<'_> {
        NpcInventoryItemTableHandle {
            imp: self.imp.get_table::<NpcInventoryItem>("npc_inventory_item"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct NpcInventoryItemInsertCallbackId(__sdk::CallbackId);
pub struct NpcInventoryItemDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for NpcInventoryItemTableHandle<'ctx> {
    type Row = NpcInventoryItem;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = NpcInventoryItem> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = NpcInventoryItemInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcInventoryItemInsertCallbackId {
        NpcInventoryItemInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: NpcInventoryItemInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = NpcInventoryItemDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> NpcInventoryItemDeleteCallbackId {
        NpcInventoryItemDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: NpcInventoryItemDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct NpcInventoryItemUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for NpcInventoryItemTableHandle<'ctx> {
    type UpdateCallbackId = NpcInventoryItemUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> NpcInventoryItemUpdateCallbackId {
        NpcInventoryItemUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: NpcInventoryItemUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `npc_inventory_item`,
/// which allows point queries on the field of the same name
/// via the [`NpcInventoryItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.npc_inventory_item().id().find(...)`.
pub struct NpcInventoryItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<NpcInventoryItem, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> NpcInventoryItemTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `npc_inventory_item`.
    pub fn id(&self) -> NpcInventoryItemIdUnique<'ctx> {
        NpcInventoryItemIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> NpcInventoryItemIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<NpcInventoryItem> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<NpcInventoryItem>("npc_inventory_item");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<NpcInventoryItem>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<NpcInventoryItem>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `NpcInventoryItem`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait npc_inventory_itemQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `NpcInventoryItem`.
    fn npc_inventory_item(&self) -> __sdk::__query_builder::Table<NpcInventoryItem>;
}

impl npc_inventory_itemQueryTableAccess for __sdk::QueryTableAccessor {
    fn npc_inventory_item(&self) -> __sdk::__query_builder::Table<NpcInventoryItem> {
        __sdk::__query_builder::Table::new("npc_inventory_item")
    }
}
