// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcInventoryItem {
    pub id: u64,
    pub npc_id: u64,
    pub slot: i32,
    pub item_def_id: u64,
    pub quantity: i32,
}

impl __sdk::InModule for NpcInventoryItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcInventoryItem`.
///
/// Provides typed access to columns for query building.
pub struct NpcInventoryItemCols {
    pub id: __sdk::__query_builder::Col<NpcInventoryItem, u64>,
    pub npc_id: __sdk::__query_builder::Col<NpcInventoryItem, u64>,
    pub slot: __sdk::__query_builder::Col<NpcInventoryItem, i32>,
    pub item_def_id: __sdk::__query_builder::Col<NpcInventoryItem, u64>,
    pub quantity: __sdk::__query_builder::Col<NpcInventoryItem, i32>,
}

impl __sdk::__query_builder::HasCols for NpcInventoryItem {
    type Cols = NpcInventoryItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcInventoryItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            slot: __sdk::__query_builder::Col::new(table_name, "slot"),
            item_def_id: __sdk::__query_builder::Col::new(table_name, "item_def_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcInventoryItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcInventoryItemIxCols {
    pub id: __sdk::__query_builder::IxCol<NpcInventoryItem, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcInventoryItem {
    type IxCols = NpcInventoryItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcInventoryItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcInventoryItem {}
