// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcKnowledge {
    pub id: u64,
    pub npc_id: u64,
    pub category: String,
    pub fact: String,
    pub learned_from: String,
    pub confidence: f32,
    pub created_at: u64,
}

impl __sdk::InModule for NpcKnowledge {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcKnowledge`.
///
/// Provides typed access to columns for query building.
pub struct NpcKnowledgeCols {
    pub id: __sdk::__query_builder::Col<NpcKnowledge, u64>,
    pub npc_id: __sdk::__query_builder::Col<NpcKnowledge, u64>,
    pub category: __sdk::__query_builder::Col<NpcKnowledge, String>,
    pub fact: __sdk::__query_builder::Col<NpcKnowledge, String>,
    pub learned_from: __sdk::__query_builder::Col<NpcKnowledge, String>,
    pub confidence: __sdk::__query_builder::Col<NpcKnowledge, f32>,
    pub created_at: __sdk::__query_builder::Col<NpcKnowledge, u64>,
}

impl __sdk::__query_builder::HasCols for NpcKnowledge {
    type Cols = NpcKnowledgeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcKnowledgeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            category: __sdk::__query_builder::Col::new(table_name, "category"),
            fact: __sdk::__query_builder::Col::new(table_name, "fact"),
            learned_from: __sdk::__query_builder::Col::new(table_name, "learned_from"),
            confidence: __sdk::__query_builder::Col::new(table_name, "confidence"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcKnowledge`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcKnowledgeIxCols {
    pub id: __sdk::__query_builder::IxCol<NpcKnowledge, u64>,
    pub npc_id: __sdk::__query_builder::IxCol<NpcKnowledge, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcKnowledge {
    type IxCols = NpcKnowledgeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcKnowledgeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            npc_id: __sdk::__query_builder::IxCol::new(table_name, "npc_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcKnowledge {}
