// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Projectile {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub owner: __sdk::Identity,
    pub skill_id: u64,
    pub start_x: f32,
    pub start_y: f32,
    pub start_z: f32,
    pub dir_x: f32,
    pub dir_z: f32,
    pub speed: f32,
    pub max_range: f32,
    pub power: i32,
    pub knockback: f32,
    pub hit_radius: f32,
    pub started_at: u64,
}

impl __sdk::InModule for Projectile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Projectile`.
///
/// Provides typed access to columns for query building.
pub struct ProjectileCols {
    pub scheduled_id: __sdk::__query_builder::Col<Projectile, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<Projectile, __sdk::ScheduleAt>,
    pub owner: __sdk::__query_builder::Col<Projectile, __sdk::Identity>,
    pub skill_id: __sdk::__query_builder::Col<Projectile, u64>,
    pub start_x: __sdk::__query_builder::Col<Projectile, f32>,
    pub start_y: __sdk::__query_builder::Col<Projectile, f32>,
    pub start_z: __sdk::__query_builder::Col<Projectile, f32>,
    pub dir_x: __sdk::__query_builder::Col<Projectile, f32>,
    pub dir_z: __sdk::__query_builder::Col<Projectile, f32>,
    pub speed: __sdk::__query_builder::Col<Projectile, f32>,
    pub max_range: __sdk::__query_builder::Col<Projectile, f32>,
    pub power: __sdk::__query_builder::Col<Projectile, i32>,
    pub knockback: __sdk::__query_builder::Col<Projectile, f32>,
    pub hit_radius: __sdk::__query_builder::Col<Projectile, f32>,
    pub started_at: __sdk::__query_builder::Col<Projectile, u64>,
}

impl __sdk::__query_builder::HasCols for Projectile {
    type Cols = ProjectileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectileCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            skill_id: __sdk::__query_builder::Col::new(table_name, "skill_id"),
            start_x: __sdk::__query_builder::Col::new(table_name, "start_x"),
            start_y: __sdk::__query_builder::Col::new(table_name, "start_y"),
            start_z: __sdk::__query_builder::Col::new(table_name, "start_z"),
            dir_x: __sdk::__query_builder::Col::new(table_name, "dir_x"),
            dir_z: __sdk::__query_builder::Col::new(table_name, "dir_z"),
            speed: __sdk::__query_builder::Col::new(table_name, "speed"),
            max_range: __sdk::__query_builder::Col::new(table_name, "max_range"),
            power: __sdk::__query_builder::Col::new(table_name, "power"),
            knockback: __sdk::__query_builder::Col::new(table_name, "knockback"),
            hit_radius: __sdk::__query_builder::Col::new(table_name, "hit_radius"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Projectile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectileIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<Projectile, u64>,
}

impl __sdk::__query_builder::HasIxCols for Projectile {
    type IxCols = ProjectileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectileIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Projectile {}
