// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeMindHistory {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub beliefs: String,
    pub relationships: String,
    pub memories: String,
    pub site_observations: String,
    pub knowledge: String,
}

impl __sdk::InModule for SimNativeMindHistory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeMindHistory`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeMindHistoryCols {
    pub key: __sdk::__query_builder::Col<SimNativeMindHistory, String>,
    pub run: __sdk::__query_builder::Col<SimNativeMindHistory, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeMindHistory, u32>,
    pub beliefs: __sdk::__query_builder::Col<SimNativeMindHistory, String>,
    pub relationships: __sdk::__query_builder::Col<SimNativeMindHistory, String>,
    pub memories: __sdk::__query_builder::Col<SimNativeMindHistory, String>,
    pub site_observations: __sdk::__query_builder::Col<SimNativeMindHistory, String>,
    pub knowledge: __sdk::__query_builder::Col<SimNativeMindHistory, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeMindHistory {
    type Cols = SimNativeMindHistoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeMindHistoryCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            beliefs: __sdk::__query_builder::Col::new(table_name, "beliefs"),
            relationships: __sdk::__query_builder::Col::new(table_name, "relationships"),
            memories: __sdk::__query_builder::Col::new(table_name, "memories"),
            site_observations: __sdk::__query_builder::Col::new(table_name, "site_observations"),
            knowledge: __sdk::__query_builder::Col::new(table_name, "knowledge"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeMindHistory`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeMindHistoryIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeMindHistory, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeMindHistory, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeMindHistory {
    type IxCols = SimNativeMindHistoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeMindHistoryIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeMindHistory {}
