// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimBeginWorldUploadArgs {
    pub run: String,
    pub mode: String,
    pub total_bytes: u32,
    pub sha_256: String,
}

impl From<SimBeginWorldUploadArgs> for super::Reducer {
    fn from(args: SimBeginWorldUploadArgs) -> Self {
        Self::SimBeginWorldUpload {
            run: args.run,
            mode: args.mode,
            total_bytes: args.total_bytes,
            sha_256: args.sha_256,
        }
    }
}

impl __sdk::InModule for SimBeginWorldUploadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_begin_world_upload`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_begin_world_upload {
    /// Request that the remote module invoke the reducer `sim_begin_world_upload` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_begin_world_upload:sim_begin_world_upload_then`] to run a callback after the reducer completes.
    fn sim_begin_world_upload(
        &self,
        run: String,
        mode: String,
        total_bytes: u32,
        sha_256: String,
    ) -> __sdk::Result<()> {
        self.sim_begin_world_upload_then(run, mode, total_bytes, sha_256, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_begin_world_upload` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_begin_world_upload_then(
        &self,
        run: String,
        mode: String,
        total_bytes: u32,
        sha_256: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_begin_world_upload for super::RemoteReducers {
    fn sim_begin_world_upload_then(
        &self,
        run: String,
        mode: String,
        total_bytes: u32,
        sha_256: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SimBeginWorldUploadArgs {
                run,
                mode,
                total_bytes,
                sha_256,
            },
            callback,
        )
    }
}
