// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimGrantClientArgs {
    pub run: String,
    pub identity: __sdk::Identity,
    pub observer: bool,
    pub actor: u32,
}

impl From<SimGrantClientArgs> for super::Reducer {
    fn from(args: SimGrantClientArgs) -> Self {
        Self::SimGrantClient {
            run: args.run,
            identity: args.identity,
            observer: args.observer,
            actor: args.actor,
        }
    }
}

impl __sdk::InModule for SimGrantClientArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_grant_client`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_grant_client {
    /// Request that the remote module invoke the reducer `sim_grant_client` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_grant_client:sim_grant_client_then`] to run a callback after the reducer completes.
    fn sim_grant_client(
        &self,
        run: String,
        identity: __sdk::Identity,
        observer: bool,
        actor: u32,
    ) -> __sdk::Result<()> {
        self.sim_grant_client_then(run, identity, observer, actor, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_grant_client` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_grant_client_then(
        &self,
        run: String,
        identity: __sdk::Identity,
        observer: bool,
        actor: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_grant_client for super::RemoteReducers {
    fn sim_grant_client_then(
        &self,
        run: String,
        identity: __sdk::Identity,
        observer: bool,
        actor: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SimGrantClientArgs {
                run,
                identity,
                observer,
                actor,
            },
            callback,
        )
    }
}
