// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_render_scene_type::SimRenderScene;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_render_scene`.
///
/// Obtain a handle from the [`SimMyRenderSceneTableAccess::sim_my_render_scene`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_render_scene()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_render_scene().on_insert(...)`.
pub struct SimMyRenderSceneTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimRenderScene>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_render_scene`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyRenderSceneTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyRenderSceneTableHandle`], which mediates access to the table `sim_my_render_scene`.
    fn sim_my_render_scene(&self) -> SimMyRenderSceneTableHandle<'_>;
}

impl SimMyRenderSceneTableAccess for super::RemoteTables {
    fn sim_my_render_scene(&self) -> SimMyRenderSceneTableHandle<'_> {
        SimMyRenderSceneTableHandle {
            imp: self.imp.get_table::<SimRenderScene>("sim_my_render_scene"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyRenderSceneInsertCallbackId(__sdk::CallbackId);
pub struct SimMyRenderSceneDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyRenderSceneTableHandle<'ctx> {
    type Row = SimRenderScene;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimRenderScene> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyRenderSceneInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderSceneInsertCallbackId {
        SimMyRenderSceneInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyRenderSceneInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyRenderSceneDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderSceneDeleteCallbackId {
        SimMyRenderSceneDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyRenderSceneDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimRenderScene>("sim_my_render_scene");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimRenderScene>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimRenderScene>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimRenderScene`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_render_sceneQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimRenderScene`.
    fn sim_my_render_scene(&self) -> __sdk::__query_builder::Table<SimRenderScene>;
}

impl sim_my_render_sceneQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_render_scene(&self) -> __sdk::__query_builder::Table<SimRenderScene> {
        __sdk::__query_builder::Table::new("sim_my_render_scene")
    }
}
