// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimClockWake {
    pub id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub run: String,
}

impl __sdk::InModule for SimClockWake {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimClockWake`.
///
/// Provides typed access to columns for query building.
pub struct SimClockWakeCols {
    pub id: __sdk::__query_builder::Col<SimClockWake, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<SimClockWake, __sdk::ScheduleAt>,
    pub run: __sdk::__query_builder::Col<SimClockWake, String>,
}

impl __sdk::__query_builder::HasCols for SimClockWake {
    type Cols = SimClockWakeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimClockWakeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
        }
    }
}

/// Indexed column accessor struct for the table `SimClockWake`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimClockWakeIxCols {
    pub id: __sdk::__query_builder::IxCol<SimClockWake, u64>,
}

impl __sdk::__query_builder::HasIxCols for SimClockWake {
    type IxCols = SimClockWakeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimClockWakeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimClockWake {}
