// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_world_upload_type::SimWorldUpload;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_world_upload`.
///
/// Obtain a handle from the [`SimMyWorldUploadTableAccess::sim_my_world_upload`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_world_upload()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_world_upload().on_insert(...)`.
pub struct SimMyWorldUploadTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimWorldUpload>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_world_upload`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyWorldUploadTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyWorldUploadTableHandle`], which mediates access to the table `sim_my_world_upload`.
    fn sim_my_world_upload(&self) -> SimMyWorldUploadTableHandle<'_>;
}

impl SimMyWorldUploadTableAccess for super::RemoteTables {
    fn sim_my_world_upload(&self) -> SimMyWorldUploadTableHandle<'_> {
        SimMyWorldUploadTableHandle {
            imp: self.imp.get_table::<SimWorldUpload>("sim_my_world_upload"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyWorldUploadInsertCallbackId(__sdk::CallbackId);
pub struct SimMyWorldUploadDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyWorldUploadTableHandle<'ctx> {
    type Row = SimWorldUpload;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimWorldUpload> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyWorldUploadInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyWorldUploadInsertCallbackId {
        SimMyWorldUploadInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyWorldUploadInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyWorldUploadDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyWorldUploadDeleteCallbackId {
        SimMyWorldUploadDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyWorldUploadDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimWorldUpload>("sim_my_world_upload");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimWorldUpload>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimWorldUpload>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimWorldUpload`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_world_uploadQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimWorldUpload`.
    fn sim_my_world_upload(&self) -> __sdk::__query_builder::Table<SimWorldUpload>;
}

impl sim_my_world_uploadQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_world_upload(&self) -> __sdk::__query_builder::Table<SimWorldUpload> {
        __sdk::__query_builder::Table::new("sim_my_world_upload")
    }
}
