// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimSetupClientClockArgs {
    pub run: String,
    pub evidence_mode: String,
}

impl From<SimSetupClientClockArgs> for super::Reducer {
    fn from(args: SimSetupClientClockArgs) -> Self {
        Self::SimSetupClientClock {
            run: args.run,
            evidence_mode: args.evidence_mode,
        }
    }
}

impl __sdk::InModule for SimSetupClientClockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_setup_client_clock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_setup_client_clock {
    /// Request that the remote module invoke the reducer `sim_setup_client_clock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_setup_client_clock:sim_setup_client_clock_then`] to run a callback after the reducer completes.
    fn sim_setup_client_clock(&self, run: String, evidence_mode: String) -> __sdk::Result<()> {
        self.sim_setup_client_clock_then(run, evidence_mode, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_setup_client_clock` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_setup_client_clock_then(
        &self,
        run: String,
        evidence_mode: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_setup_client_clock for super::RemoteReducers {
    fn sim_setup_client_clock_then(
        &self,
        run: String,
        evidence_mode: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SimSetupClientClockArgs { run, evidence_mode }, callback)
    }
}
