// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimPhysicalClock {
    pub run: String,
    pub enabled: bool,
    pub next_world_ms: u64,
    pub alive: u64,
    pub pending_id: u64,
    pub world_deadline: __sdk::Timestamp,
    pub action_transactions: u64,
    pub world_transactions: u64,
    pub action_actors_loaded: u64,
    pub max_action_actors_loaded: u64,
}

impl __sdk::InModule for SimPhysicalClock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimPhysicalClock`.
///
/// Provides typed access to columns for query building.
pub struct SimPhysicalClockCols {
    pub run: __sdk::__query_builder::Col<SimPhysicalClock, String>,
    pub enabled: __sdk::__query_builder::Col<SimPhysicalClock, bool>,
    pub next_world_ms: __sdk::__query_builder::Col<SimPhysicalClock, u64>,
    pub alive: __sdk::__query_builder::Col<SimPhysicalClock, u64>,
    pub pending_id: __sdk::__query_builder::Col<SimPhysicalClock, u64>,
    pub world_deadline: __sdk::__query_builder::Col<SimPhysicalClock, __sdk::Timestamp>,
    pub action_transactions: __sdk::__query_builder::Col<SimPhysicalClock, u64>,
    pub world_transactions: __sdk::__query_builder::Col<SimPhysicalClock, u64>,
    pub action_actors_loaded: __sdk::__query_builder::Col<SimPhysicalClock, u64>,
    pub max_action_actors_loaded: __sdk::__query_builder::Col<SimPhysicalClock, u64>,
}

impl __sdk::__query_builder::HasCols for SimPhysicalClock {
    type Cols = SimPhysicalClockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimPhysicalClockCols {
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            enabled: __sdk::__query_builder::Col::new(table_name, "enabled"),
            next_world_ms: __sdk::__query_builder::Col::new(table_name, "next_world_ms"),
            alive: __sdk::__query_builder::Col::new(table_name, "alive"),
            pending_id: __sdk::__query_builder::Col::new(table_name, "pending_id"),
            world_deadline: __sdk::__query_builder::Col::new(table_name, "world_deadline"),
            action_transactions: __sdk::__query_builder::Col::new(
                table_name,
                "action_transactions",
            ),
            world_transactions: __sdk::__query_builder::Col::new(table_name, "world_transactions"),
            action_actors_loaded: __sdk::__query_builder::Col::new(
                table_name,
                "action_actors_loaded",
            ),
            max_action_actors_loaded: __sdk::__query_builder::Col::new(
                table_name,
                "max_action_actors_loaded",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `SimPhysicalClock`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimPhysicalClockIxCols {
    pub run: __sdk::__query_builder::IxCol<SimPhysicalClock, String>,
}

impl __sdk::__query_builder::HasIxCols for SimPhysicalClock {
    type IxCols = SimPhysicalClockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimPhysicalClockIxCols {
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimPhysicalClock {}
