// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimWorldUploadChunk {
    pub key: String,
    pub run: String,
    pub index: u32,
    pub body: String,
}

impl __sdk::InModule for SimWorldUploadChunk {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimWorldUploadChunk`.
///
/// Provides typed access to columns for query building.
pub struct SimWorldUploadChunkCols {
    pub key: __sdk::__query_builder::Col<SimWorldUploadChunk, String>,
    pub run: __sdk::__query_builder::Col<SimWorldUploadChunk, String>,
    pub index: __sdk::__query_builder::Col<SimWorldUploadChunk, u32>,
    pub body: __sdk::__query_builder::Col<SimWorldUploadChunk, String>,
}

impl __sdk::__query_builder::HasCols for SimWorldUploadChunk {
    type Cols = SimWorldUploadChunkCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimWorldUploadChunkCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            index: __sdk::__query_builder::Col::new(table_name, "index"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
        }
    }
}

/// Indexed column accessor struct for the table `SimWorldUploadChunk`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimWorldUploadChunkIxCols {
    pub key: __sdk::__query_builder::IxCol<SimWorldUploadChunk, String>,
    pub run: __sdk::__query_builder::IxCol<SimWorldUploadChunk, String>,
}

impl __sdk::__query_builder::HasIxCols for SimWorldUploadChunk {
    type IxCols = SimWorldUploadChunkIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimWorldUploadChunkIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimWorldUploadChunk {}
