// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_controller_bootstrap_type::SimControllerBootstrap;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_controller_bootstrap`.
///
/// Obtain a handle from the [`SimMyControllerBootstrapTableAccess::sim_my_controller_bootstrap`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_controller_bootstrap()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_controller_bootstrap().on_insert(...)`.
pub struct SimMyControllerBootstrapTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimControllerBootstrap>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_controller_bootstrap`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyControllerBootstrapTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyControllerBootstrapTableHandle`], which mediates access to the table `sim_my_controller_bootstrap`.
    fn sim_my_controller_bootstrap(&self) -> SimMyControllerBootstrapTableHandle<'_>;
}

impl SimMyControllerBootstrapTableAccess for super::RemoteTables {
    fn sim_my_controller_bootstrap(&self) -> SimMyControllerBootstrapTableHandle<'_> {
        SimMyControllerBootstrapTableHandle {
            imp: self
                .imp
                .get_table::<SimControllerBootstrap>("sim_my_controller_bootstrap"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyControllerBootstrapInsertCallbackId(__sdk::CallbackId);
pub struct SimMyControllerBootstrapDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyControllerBootstrapTableHandle<'ctx> {
    type Row = SimControllerBootstrap;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimControllerBootstrap> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyControllerBootstrapInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyControllerBootstrapInsertCallbackId {
        SimMyControllerBootstrapInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyControllerBootstrapInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyControllerBootstrapDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyControllerBootstrapDeleteCallbackId {
        SimMyControllerBootstrapDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyControllerBootstrapDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<SimControllerBootstrap>("sim_my_controller_bootstrap");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimControllerBootstrap>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimControllerBootstrap>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimControllerBootstrap`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_controller_bootstrapQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimControllerBootstrap`.
    fn sim_my_controller_bootstrap(&self) -> __sdk::__query_builder::Table<SimControllerBootstrap>;
}

impl sim_my_controller_bootstrapQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_controller_bootstrap(&self) -> __sdk::__query_builder::Table<SimControllerBootstrap> {
        __sdk::__query_builder::Table::new("sim_my_controller_bootstrap")
    }
}
