// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimControllerFrame {
    pub run: String,
    pub actor: u32,
    pub tick: u64,
    pub stopped: bool,
    pub paused: bool,
    pub control_epoch: u64,
    pub revision: u64,
    pub position: i32,
    pub health: i32,
    pub hunger: i32,
    pub energy: i32,
    pub food: i32,
    pub fear: i32,
    pub failures: u32,
    pub action: String,
    pub body: Option<String>,
    pub materials: Option<String>,
    pub action_ready_ms: u64,
}

impl __sdk::InModule for SimControllerFrame {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimControllerFrame`.
///
/// Provides typed access to columns for query building.
pub struct SimControllerFrameCols {
    pub run: __sdk::__query_builder::Col<SimControllerFrame, String>,
    pub actor: __sdk::__query_builder::Col<SimControllerFrame, u32>,
    pub tick: __sdk::__query_builder::Col<SimControllerFrame, u64>,
    pub stopped: __sdk::__query_builder::Col<SimControllerFrame, bool>,
    pub paused: __sdk::__query_builder::Col<SimControllerFrame, bool>,
    pub control_epoch: __sdk::__query_builder::Col<SimControllerFrame, u64>,
    pub revision: __sdk::__query_builder::Col<SimControllerFrame, u64>,
    pub position: __sdk::__query_builder::Col<SimControllerFrame, i32>,
    pub health: __sdk::__query_builder::Col<SimControllerFrame, i32>,
    pub hunger: __sdk::__query_builder::Col<SimControllerFrame, i32>,
    pub energy: __sdk::__query_builder::Col<SimControllerFrame, i32>,
    pub food: __sdk::__query_builder::Col<SimControllerFrame, i32>,
    pub fear: __sdk::__query_builder::Col<SimControllerFrame, i32>,
    pub failures: __sdk::__query_builder::Col<SimControllerFrame, u32>,
    pub action: __sdk::__query_builder::Col<SimControllerFrame, String>,
    pub body: __sdk::__query_builder::Col<SimControllerFrame, Option<String>>,
    pub materials: __sdk::__query_builder::Col<SimControllerFrame, Option<String>>,
    pub action_ready_ms: __sdk::__query_builder::Col<SimControllerFrame, u64>,
}

impl __sdk::__query_builder::HasCols for SimControllerFrame {
    type Cols = SimControllerFrameCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimControllerFrameCols {
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            stopped: __sdk::__query_builder::Col::new(table_name, "stopped"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),
            control_epoch: __sdk::__query_builder::Col::new(table_name, "control_epoch"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            hunger: __sdk::__query_builder::Col::new(table_name, "hunger"),
            energy: __sdk::__query_builder::Col::new(table_name, "energy"),
            food: __sdk::__query_builder::Col::new(table_name, "food"),
            fear: __sdk::__query_builder::Col::new(table_name, "fear"),
            failures: __sdk::__query_builder::Col::new(table_name, "failures"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
            materials: __sdk::__query_builder::Col::new(table_name, "materials"),
            action_ready_ms: __sdk::__query_builder::Col::new(table_name, "action_ready_ms"),
        }
    }
}
