// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_client_snapshot_type::SimClientSnapshot;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_render_header`.
///
/// Obtain a handle from the [`SimMyRenderHeaderTableAccess::sim_my_render_header`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_render_header()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_render_header().on_insert(...)`.
pub struct SimMyRenderHeaderTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimClientSnapshot>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_render_header`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyRenderHeaderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyRenderHeaderTableHandle`], which mediates access to the table `sim_my_render_header`.
    fn sim_my_render_header(&self) -> SimMyRenderHeaderTableHandle<'_>;
}

impl SimMyRenderHeaderTableAccess for super::RemoteTables {
    fn sim_my_render_header(&self) -> SimMyRenderHeaderTableHandle<'_> {
        SimMyRenderHeaderTableHandle {
            imp: self
                .imp
                .get_table::<SimClientSnapshot>("sim_my_render_header"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyRenderHeaderInsertCallbackId(__sdk::CallbackId);
pub struct SimMyRenderHeaderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyRenderHeaderTableHandle<'ctx> {
    type Row = SimClientSnapshot;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimClientSnapshot> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyRenderHeaderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderHeaderInsertCallbackId {
        SimMyRenderHeaderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyRenderHeaderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyRenderHeaderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderHeaderDeleteCallbackId {
        SimMyRenderHeaderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyRenderHeaderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimClientSnapshot>("sim_my_render_header");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimClientSnapshot>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimClientSnapshot>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimClientSnapshot`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_render_headerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimClientSnapshot`.
    fn sim_my_render_header(&self) -> __sdk::__query_builder::Table<SimClientSnapshot>;
}

impl sim_my_render_headerQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_render_header(&self) -> __sdk::__query_builder::Table<SimClientSnapshot> {
        __sdk::__query_builder::Table::new("sim_my_render_header")
    }
}
