// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimClientControlArgs {
    pub command: String,
}

impl From<SimClientControlArgs> for super::Reducer {
    fn from(args: SimClientControlArgs) -> Self {
        Self::SimClientControl {
            command: args.command,
        }
    }
}

impl __sdk::InModule for SimClientControlArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_client_control`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_client_control {
    /// Request that the remote module invoke the reducer `sim_client_control` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_client_control:sim_client_control_then`] to run a callback after the reducer completes.
    fn sim_client_control(&self, command: String) -> __sdk::Result<()> {
        self.sim_client_control_then(command, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_client_control` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_client_control_then(
        &self,
        command: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_client_control for super::RemoteReducers {
    fn sim_client_control_then(
        &self,
        command: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SimClientControlArgs { command }, callback)
    }
}
