// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeEvidenceBody {
    pub id: u64,
    pub digest: String,
    pub run: String,
    pub data: String,
}

impl __sdk::InModule for SimNativeEvidenceBody {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeEvidenceBody`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeEvidenceBodyCols {
    pub id: __sdk::__query_builder::Col<SimNativeEvidenceBody, u64>,
    pub digest: __sdk::__query_builder::Col<SimNativeEvidenceBody, String>,
    pub run: __sdk::__query_builder::Col<SimNativeEvidenceBody, String>,
    pub data: __sdk::__query_builder::Col<SimNativeEvidenceBody, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeEvidenceBody {
    type Cols = SimNativeEvidenceBodyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeEvidenceBodyCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            digest: __sdk::__query_builder::Col::new(table_name, "digest"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeEvidenceBody`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeEvidenceBodyIxCols {
    pub digest: __sdk::__query_builder::IxCol<SimNativeEvidenceBody, String>,
    pub id: __sdk::__query_builder::IxCol<SimNativeEvidenceBody, u64>,
    pub run: __sdk::__query_builder::IxCol<SimNativeEvidenceBody, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeEvidenceBody {
    type IxCols = SimNativeEvidenceBodyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeEvidenceBodyIxCols {
            digest: __sdk::__query_builder::IxCol::new(table_name, "digest"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeEvidenceBody {}
