// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimDispatchControllerActionAfterArgs {
    pub sequence: u64,
    pub request: String,
    pub cursor: u64,
}

impl From<SimDispatchControllerActionAfterArgs> for super::Reducer {
    fn from(args: SimDispatchControllerActionAfterArgs) -> Self {
        Self::SimDispatchControllerActionAfter {
            sequence: args.sequence,
            request: args.request,
            cursor: args.cursor,
        }
    }
}

impl __sdk::InModule for SimDispatchControllerActionAfterArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_dispatch_controller_action_after`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_dispatch_controller_action_after {
    /// Request that the remote module invoke the reducer `sim_dispatch_controller_action_after` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_dispatch_controller_action_after:sim_dispatch_controller_action_after_then`] to run a callback after the reducer completes.
    fn sim_dispatch_controller_action_after(
        &self,
        sequence: u64,
        request: String,
        cursor: u64,
    ) -> __sdk::Result<()> {
        self.sim_dispatch_controller_action_after_then(sequence, request, cursor, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_dispatch_controller_action_after` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_dispatch_controller_action_after_then(
        &self,
        sequence: u64,
        request: String,
        cursor: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_dispatch_controller_action_after for super::RemoteReducers {
    fn sim_dispatch_controller_action_after_then(
        &self,
        sequence: u64,
        request: String,
        cursor: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SimDispatchControllerActionAfterArgs {
                sequence,
                request,
                cursor,
            },
            callback,
        )
    }
}
