// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimAuditBlock {
    pub key: String,
    pub run: String,
    pub first: u64,
    pub last: u64,
    pub plain_bytes: u64,
    pub digest: String,
    pub zlib: Vec<u8>,
}

impl __sdk::InModule for SimAuditBlock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimAuditBlock`.
///
/// Provides typed access to columns for query building.
pub struct SimAuditBlockCols {
    pub key: __sdk::__query_builder::Col<SimAuditBlock, String>,
    pub run: __sdk::__query_builder::Col<SimAuditBlock, String>,
    pub first: __sdk::__query_builder::Col<SimAuditBlock, u64>,
    pub last: __sdk::__query_builder::Col<SimAuditBlock, u64>,
    pub plain_bytes: __sdk::__query_builder::Col<SimAuditBlock, u64>,
    pub digest: __sdk::__query_builder::Col<SimAuditBlock, String>,
    pub zlib: __sdk::__query_builder::Col<SimAuditBlock, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for SimAuditBlock {
    type Cols = SimAuditBlockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimAuditBlockCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            first: __sdk::__query_builder::Col::new(table_name, "first"),
            last: __sdk::__query_builder::Col::new(table_name, "last"),
            plain_bytes: __sdk::__query_builder::Col::new(table_name, "plain_bytes"),
            digest: __sdk::__query_builder::Col::new(table_name, "digest"),
            zlib: __sdk::__query_builder::Col::new(table_name, "zlib"),
        }
    }
}

/// Indexed column accessor struct for the table `SimAuditBlock`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimAuditBlockIxCols {
    pub key: __sdk::__query_builder::IxCol<SimAuditBlock, String>,
    pub run: __sdk::__query_builder::IxCol<SimAuditBlock, String>,
}

impl __sdk::__query_builder::HasIxCols for SimAuditBlock {
    type IxCols = SimAuditBlockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimAuditBlockIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimAuditBlock {}
