// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_controller_frame_type::SimControllerFrame;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_controller_frame`.
///
/// Obtain a handle from the [`SimMyControllerFrameTableAccess::sim_my_controller_frame`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_controller_frame()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_controller_frame().on_insert(...)`.
pub struct SimMyControllerFrameTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimControllerFrame>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_controller_frame`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyControllerFrameTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyControllerFrameTableHandle`], which mediates access to the table `sim_my_controller_frame`.
    fn sim_my_controller_frame(&self) -> SimMyControllerFrameTableHandle<'_>;
}

impl SimMyControllerFrameTableAccess for super::RemoteTables {
    fn sim_my_controller_frame(&self) -> SimMyControllerFrameTableHandle<'_> {
        SimMyControllerFrameTableHandle {
            imp: self
                .imp
                .get_table::<SimControllerFrame>("sim_my_controller_frame"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyControllerFrameInsertCallbackId(__sdk::CallbackId);
pub struct SimMyControllerFrameDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyControllerFrameTableHandle<'ctx> {
    type Row = SimControllerFrame;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimControllerFrame> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyControllerFrameInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyControllerFrameInsertCallbackId {
        SimMyControllerFrameInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyControllerFrameInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyControllerFrameDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyControllerFrameDeleteCallbackId {
        SimMyControllerFrameDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyControllerFrameDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimControllerFrame>("sim_my_controller_frame");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimControllerFrame>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimControllerFrame>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimControllerFrame`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_controller_frameQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimControllerFrame`.
    fn sim_my_controller_frame(&self) -> __sdk::__query_builder::Table<SimControllerFrame>;
}

impl sim_my_controller_frameQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_controller_frame(&self) -> __sdk::__query_builder::Table<SimControllerFrame> {
        __sdk::__query_builder::Table::new("sim_my_controller_frame")
    }
}
