// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimWorldBuild {
    pub run: String,
    pub owner: __sdk::Identity,
    pub phase: String,
    pub cursor: u64,
    pub step: u64,
    pub kernel: String,
}

impl __sdk::InModule for SimWorldBuild {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimWorldBuild`.
///
/// Provides typed access to columns for query building.
pub struct SimWorldBuildCols {
    pub run: __sdk::__query_builder::Col<SimWorldBuild, String>,
    pub owner: __sdk::__query_builder::Col<SimWorldBuild, __sdk::Identity>,
    pub phase: __sdk::__query_builder::Col<SimWorldBuild, String>,
    pub cursor: __sdk::__query_builder::Col<SimWorldBuild, u64>,
    pub step: __sdk::__query_builder::Col<SimWorldBuild, u64>,
    pub kernel: __sdk::__query_builder::Col<SimWorldBuild, String>,
}

impl __sdk::__query_builder::HasCols for SimWorldBuild {
    type Cols = SimWorldBuildCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimWorldBuildCols {
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            phase: __sdk::__query_builder::Col::new(table_name, "phase"),
            cursor: __sdk::__query_builder::Col::new(table_name, "cursor"),
            step: __sdk::__query_builder::Col::new(table_name, "step"),
            kernel: __sdk::__query_builder::Col::new(table_name, "kernel"),
        }
    }
}

/// Indexed column accessor struct for the table `SimWorldBuild`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimWorldBuildIxCols {
    pub owner: __sdk::__query_builder::IxCol<SimWorldBuild, __sdk::Identity>,
    pub run: __sdk::__query_builder::IxCol<SimWorldBuild, String>,
}

impl __sdk::__query_builder::HasIxCols for SimWorldBuild {
    type IxCols = SimWorldBuildIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimWorldBuildIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimWorldBuild {}
