// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct SimExportOwnedAuditArgs {
    pub run: String,
    pub start: u64,
    pub end: u64,
    pub limit: u32,
}

impl __sdk::InModule for SimExportOwnedAuditArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `sim_export_owned_audit`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait sim_export_owned_audit {
    fn sim_export_owned_audit(&self, run: String, start: u64, end: u64, limit: u32) {
        self.sim_export_owned_audit_then(run, start, end, limit, |_, _| {});
    }

    fn sim_export_owned_audit_then(
        &self,
        run: String,
        start: u64,
        end: u64,
        limit: u32,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Vec<String>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    );
}

impl sim_export_owned_audit for super::RemoteProcedures {
    fn sim_export_owned_audit_then(
        &self,
        run: String,
        start: u64,
        end: u64,
        limit: u32,

        __callback: impl FnOnce(
                &super::ProcedureEventContext,
                Result<Result<Vec<String>, String>, __sdk::InternalError>,
            ) + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<Vec<String>, String>>(
                "sim_export_owned_audit",
                SimExportOwnedAuditArgs {
                    run,
                    start,
                    end,
                    limit,
                },
                __callback,
            );
    }
}
