// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimAuditWake {
    pub id: u64,
    pub run: String,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for SimAuditWake {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimAuditWake`.
///
/// Provides typed access to columns for query building.
pub struct SimAuditWakeCols {
    pub id: __sdk::__query_builder::Col<SimAuditWake, u64>,
    pub run: __sdk::__query_builder::Col<SimAuditWake, String>,
    pub scheduled_at: __sdk::__query_builder::Col<SimAuditWake, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for SimAuditWake {
    type Cols = SimAuditWakeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimAuditWakeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SimAuditWake`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimAuditWakeIxCols {
    pub id: __sdk::__query_builder::IxCol<SimAuditWake, u64>,
    pub run: __sdk::__query_builder::IxCol<SimAuditWake, String>,
}

impl __sdk::__query_builder::HasIxCols for SimAuditWake {
    type IxCols = SimAuditWakeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimAuditWakeIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimAuditWake {}
