// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimConfigurePhysicalClockArgs {
    pub run: String,
    pub enabled: bool,
}

impl From<SimConfigurePhysicalClockArgs> for super::Reducer {
    fn from(args: SimConfigurePhysicalClockArgs) -> Self {
        Self::SimConfigurePhysicalClock {
            run: args.run,
            enabled: args.enabled,
        }
    }
}

impl __sdk::InModule for SimConfigurePhysicalClockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_configure_physical_clock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_configure_physical_clock {
    /// Request that the remote module invoke the reducer `sim_configure_physical_clock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_configure_physical_clock:sim_configure_physical_clock_then`] to run a callback after the reducer completes.
    fn sim_configure_physical_clock(&self, run: String, enabled: bool) -> __sdk::Result<()> {
        self.sim_configure_physical_clock_then(run, enabled, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_configure_physical_clock` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_configure_physical_clock_then(
        &self,
        run: String,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_configure_physical_clock for super::RemoteReducers {
    fn sim_configure_physical_clock_then(
        &self,
        run: String,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SimConfigurePhysicalClockArgs { run, enabled }, callback)
    }
}
