// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeSite {
    pub key: String,
    pub run: String,
    pub ordinal: u32,
    pub position: i32,
    pub food: i32,
    pub hazard: i32,
    pub shelter: i32,
}

impl __sdk::InModule for SimNativeSite {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeSite`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeSiteCols {
    pub key: __sdk::__query_builder::Col<SimNativeSite, String>,
    pub run: __sdk::__query_builder::Col<SimNativeSite, String>,
    pub ordinal: __sdk::__query_builder::Col<SimNativeSite, u32>,
    pub position: __sdk::__query_builder::Col<SimNativeSite, i32>,
    pub food: __sdk::__query_builder::Col<SimNativeSite, i32>,
    pub hazard: __sdk::__query_builder::Col<SimNativeSite, i32>,
    pub shelter: __sdk::__query_builder::Col<SimNativeSite, i32>,
}

impl __sdk::__query_builder::HasCols for SimNativeSite {
    type Cols = SimNativeSiteCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeSiteCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            ordinal: __sdk::__query_builder::Col::new(table_name, "ordinal"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            food: __sdk::__query_builder::Col::new(table_name, "food"),
            hazard: __sdk::__query_builder::Col::new(table_name, "hazard"),
            shelter: __sdk::__query_builder::Col::new(table_name, "shelter"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeSite`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeSiteIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeSite, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeSite, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeSite {
    type IxCols = SimNativeSiteIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeSiteIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeSite {}
