// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimRenderBodySupport {
    pub run: String,
    pub actor: u32,
    pub arena: Option<String>,
    pub body: Option<String>,
}

impl __sdk::InModule for SimRenderBodySupport {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimRenderBodySupport`.
///
/// Provides typed access to columns for query building.
pub struct SimRenderBodySupportCols {
    pub run: __sdk::__query_builder::Col<SimRenderBodySupport, String>,
    pub actor: __sdk::__query_builder::Col<SimRenderBodySupport, u32>,
    pub arena: __sdk::__query_builder::Col<SimRenderBodySupport, Option<String>>,
    pub body: __sdk::__query_builder::Col<SimRenderBodySupport, Option<String>>,
}

impl __sdk::__query_builder::HasCols for SimRenderBodySupport {
    type Cols = SimRenderBodySupportCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimRenderBodySupportCols {
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            arena: __sdk::__query_builder::Col::new(table_name, "arena"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
        }
    }
}
