// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeTraceHead {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub pages: Vec<u64>,
}

impl __sdk::InModule for SimNativeTraceHead {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeTraceHead`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeTraceHeadCols {
    pub key: __sdk::__query_builder::Col<SimNativeTraceHead, String>,
    pub run: __sdk::__query_builder::Col<SimNativeTraceHead, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeTraceHead, u32>,
    pub pages: __sdk::__query_builder::Col<SimNativeTraceHead, Vec<u64>>,
}

impl __sdk::__query_builder::HasCols for SimNativeTraceHead {
    type Cols = SimNativeTraceHeadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeTraceHeadCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            pages: __sdk::__query_builder::Col::new(table_name, "pages"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeTraceHead`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeTraceHeadIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeTraceHead, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeTraceHead, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeTraceHead {
    type IxCols = SimNativeTraceHeadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeTraceHeadIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeTraceHead {}
