// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeDefinitionVersion {
    pub key: String,
    pub digest: String,
}

impl __sdk::InModule for SimNativeDefinitionVersion {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeDefinitionVersion`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeDefinitionVersionCols {
    pub key: __sdk::__query_builder::Col<SimNativeDefinitionVersion, String>,
    pub digest: __sdk::__query_builder::Col<SimNativeDefinitionVersion, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeDefinitionVersion {
    type Cols = SimNativeDefinitionVersionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeDefinitionVersionCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            digest: __sdk::__query_builder::Col::new(table_name, "digest"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeDefinitionVersion`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeDefinitionVersionIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeDefinitionVersion, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeDefinitionVersion {
    type IxCols = SimNativeDefinitionVersionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeDefinitionVersionIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeDefinitionVersion {}
