// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeArchive {
    pub key: String,
    pub run: String,
    pub archive: u32,
    pub ordinal: u32,
    pub position: i32,
    pub label: String,
    pub capacity: u64,
    pub destroyed: bool,
    pub revision: u64,
    pub records: String,
}

impl __sdk::InModule for SimNativeArchive {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeArchive`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeArchiveCols {
    pub key: __sdk::__query_builder::Col<SimNativeArchive, String>,
    pub run: __sdk::__query_builder::Col<SimNativeArchive, String>,
    pub archive: __sdk::__query_builder::Col<SimNativeArchive, u32>,
    pub ordinal: __sdk::__query_builder::Col<SimNativeArchive, u32>,
    pub position: __sdk::__query_builder::Col<SimNativeArchive, i32>,
    pub label: __sdk::__query_builder::Col<SimNativeArchive, String>,
    pub capacity: __sdk::__query_builder::Col<SimNativeArchive, u64>,
    pub destroyed: __sdk::__query_builder::Col<SimNativeArchive, bool>,
    pub revision: __sdk::__query_builder::Col<SimNativeArchive, u64>,
    pub records: __sdk::__query_builder::Col<SimNativeArchive, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeArchive {
    type Cols = SimNativeArchiveCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeArchiveCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            archive: __sdk::__query_builder::Col::new(table_name, "archive"),
            ordinal: __sdk::__query_builder::Col::new(table_name, "ordinal"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            label: __sdk::__query_builder::Col::new(table_name, "label"),
            capacity: __sdk::__query_builder::Col::new(table_name, "capacity"),
            destroyed: __sdk::__query_builder::Col::new(table_name, "destroyed"),
            revision: __sdk::__query_builder::Col::new(table_name, "revision"),
            records: __sdk::__query_builder::Col::new(table_name, "records"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeArchive`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeArchiveIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeArchive, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeArchive, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeArchive {
    type IxCols = SimNativeArchiveIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeArchiveIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeArchive {}
