// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sim_native_trace_entry_type::SimNativeTraceEntry;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeTraceIndex {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub entries: Vec<SimNativeTraceEntry>,
}

impl __sdk::InModule for SimNativeTraceIndex {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeTraceIndex`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeTraceIndexCols {
    pub key: __sdk::__query_builder::Col<SimNativeTraceIndex, String>,
    pub run: __sdk::__query_builder::Col<SimNativeTraceIndex, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeTraceIndex, u32>,
    pub entries: __sdk::__query_builder::Col<SimNativeTraceIndex, Vec<SimNativeTraceEntry>>,
}

impl __sdk::__query_builder::HasCols for SimNativeTraceIndex {
    type Cols = SimNativeTraceIndexCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeTraceIndexCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            entries: __sdk::__query_builder::Col::new(table_name, "entries"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeTraceIndex`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeTraceIndexIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeTraceIndex, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeTraceIndex, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeTraceIndex {
    type IxCols = SimNativeTraceIndexIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeTraceIndexIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeTraceIndex {}
