// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimRenderActorSupport {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub arena: Option<String>,
    pub lifecycle: Option<String>,
    pub offer: Option<String>,
    pub body: Option<String>,
    pub materials: Option<String>,
}

impl __sdk::InModule for SimRenderActorSupport {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimRenderActorSupport`.
///
/// Provides typed access to columns for query building.
pub struct SimRenderActorSupportCols {
    pub key: __sdk::__query_builder::Col<SimRenderActorSupport, String>,
    pub run: __sdk::__query_builder::Col<SimRenderActorSupport, String>,
    pub actor: __sdk::__query_builder::Col<SimRenderActorSupport, u32>,
    pub arena: __sdk::__query_builder::Col<SimRenderActorSupport, Option<String>>,
    pub lifecycle: __sdk::__query_builder::Col<SimRenderActorSupport, Option<String>>,
    pub offer: __sdk::__query_builder::Col<SimRenderActorSupport, Option<String>>,
    pub body: __sdk::__query_builder::Col<SimRenderActorSupport, Option<String>>,
    pub materials: __sdk::__query_builder::Col<SimRenderActorSupport, Option<String>>,
}

impl __sdk::__query_builder::HasCols for SimRenderActorSupport {
    type Cols = SimRenderActorSupportCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimRenderActorSupportCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            arena: __sdk::__query_builder::Col::new(table_name, "arena"),
            lifecycle: __sdk::__query_builder::Col::new(table_name, "lifecycle"),
            offer: __sdk::__query_builder::Col::new(table_name, "offer"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
            materials: __sdk::__query_builder::Col::new(table_name, "materials"),
        }
    }
}

/// Indexed column accessor struct for the table `SimRenderActorSupport`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimRenderActorSupportIxCols {
    pub key: __sdk::__query_builder::IxCol<SimRenderActorSupport, String>,
    pub run: __sdk::__query_builder::IxCol<SimRenderActorSupport, String>,
}

impl __sdk::__query_builder::HasIxCols for SimRenderActorSupport {
    type IxCols = SimRenderActorSupportIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimRenderActorSupportIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimRenderActorSupport {}
