// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimParticipantHead {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub tick: u64,
    pub stopped: bool,
    pub latest_cursor: u64,
    pub oldest_cursor: u64,
    pub control_epoch: u64,
    pub policy_revision: u64,
    pub learning_revision: u64,
    pub health: i32,
}

impl __sdk::InModule for SimParticipantHead {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimParticipantHead`.
///
/// Provides typed access to columns for query building.
pub struct SimParticipantHeadCols {
    pub key: __sdk::__query_builder::Col<SimParticipantHead, String>,
    pub run: __sdk::__query_builder::Col<SimParticipantHead, String>,
    pub actor: __sdk::__query_builder::Col<SimParticipantHead, u32>,
    pub tick: __sdk::__query_builder::Col<SimParticipantHead, u64>,
    pub stopped: __sdk::__query_builder::Col<SimParticipantHead, bool>,
    pub latest_cursor: __sdk::__query_builder::Col<SimParticipantHead, u64>,
    pub oldest_cursor: __sdk::__query_builder::Col<SimParticipantHead, u64>,
    pub control_epoch: __sdk::__query_builder::Col<SimParticipantHead, u64>,
    pub policy_revision: __sdk::__query_builder::Col<SimParticipantHead, u64>,
    pub learning_revision: __sdk::__query_builder::Col<SimParticipantHead, u64>,
    pub health: __sdk::__query_builder::Col<SimParticipantHead, i32>,
}

impl __sdk::__query_builder::HasCols for SimParticipantHead {
    type Cols = SimParticipantHeadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimParticipantHeadCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            stopped: __sdk::__query_builder::Col::new(table_name, "stopped"),
            latest_cursor: __sdk::__query_builder::Col::new(table_name, "latest_cursor"),
            oldest_cursor: __sdk::__query_builder::Col::new(table_name, "oldest_cursor"),
            control_epoch: __sdk::__query_builder::Col::new(table_name, "control_epoch"),
            policy_revision: __sdk::__query_builder::Col::new(table_name, "policy_revision"),
            learning_revision: __sdk::__query_builder::Col::new(table_name, "learning_revision"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
        }
    }
}

/// Indexed column accessor struct for the table `SimParticipantHead`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimParticipantHeadIxCols {
    pub key: __sdk::__query_builder::IxCol<SimParticipantHead, String>,
}

impl __sdk::__query_builder::HasIxCols for SimParticipantHead {
    type IxCols = SimParticipantHeadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimParticipantHeadIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimParticipantHead {}
