// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimStageScriptsArgs {
    pub run: String,
    pub update: String,
}

impl From<SimStageScriptsArgs> for super::Reducer {
    fn from(args: SimStageScriptsArgs) -> Self {
        Self::SimStageScripts {
            run: args.run,
            update: args.update,
        }
    }
}

impl __sdk::InModule for SimStageScriptsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_stage_scripts`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_stage_scripts {
    /// Request that the remote module invoke the reducer `sim_stage_scripts` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_stage_scripts:sim_stage_scripts_then`] to run a callback after the reducer completes.
    fn sim_stage_scripts(&self, run: String, update: String) -> __sdk::Result<()> {
        self.sim_stage_scripts_then(run, update, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_stage_scripts` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_stage_scripts_then(
        &self,
        run: String,
        update: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_stage_scripts for super::RemoteReducers {
    fn sim_stage_scripts_then(
        &self,
        run: String,
        update: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SimStageScriptsArgs { run, update }, callback)
    }
}
