// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeActor {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub ordinal: u32,
    pub name: String,
    pub human: bool,
    pub position: i32,
    pub health: i32,
    pub hunger: i32,
    pub energy: i32,
    pub food: i32,
}

impl __sdk::InModule for SimNativeActor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeActor`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeActorCols {
    pub key: __sdk::__query_builder::Col<SimNativeActor, String>,
    pub run: __sdk::__query_builder::Col<SimNativeActor, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeActor, u32>,
    pub ordinal: __sdk::__query_builder::Col<SimNativeActor, u32>,
    pub name: __sdk::__query_builder::Col<SimNativeActor, String>,
    pub human: __sdk::__query_builder::Col<SimNativeActor, bool>,
    pub position: __sdk::__query_builder::Col<SimNativeActor, i32>,
    pub health: __sdk::__query_builder::Col<SimNativeActor, i32>,
    pub hunger: __sdk::__query_builder::Col<SimNativeActor, i32>,
    pub energy: __sdk::__query_builder::Col<SimNativeActor, i32>,
    pub food: __sdk::__query_builder::Col<SimNativeActor, i32>,
}

impl __sdk::__query_builder::HasCols for SimNativeActor {
    type Cols = SimNativeActorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeActorCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            ordinal: __sdk::__query_builder::Col::new(table_name, "ordinal"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            human: __sdk::__query_builder::Col::new(table_name, "human"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            health: __sdk::__query_builder::Col::new(table_name, "health"),
            hunger: __sdk::__query_builder::Col::new(table_name, "hunger"),
            energy: __sdk::__query_builder::Col::new(table_name, "energy"),
            food: __sdk::__query_builder::Col::new(table_name, "food"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeActor`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeActorIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeActor, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeActor, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeActor {
    type IxCols = SimNativeActorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeActorIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeActor {}
