// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_client_render_event_type::SimClientRenderEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_render_events`.
///
/// Obtain a handle from the [`SimMyRenderEventsTableAccess::sim_my_render_events`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_render_events()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_render_events().on_insert(...)`.
pub struct SimMyRenderEventsTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimClientRenderEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_render_events`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyRenderEventsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyRenderEventsTableHandle`], which mediates access to the table `sim_my_render_events`.
    fn sim_my_render_events(&self) -> SimMyRenderEventsTableHandle<'_>;
}

impl SimMyRenderEventsTableAccess for super::RemoteTables {
    fn sim_my_render_events(&self) -> SimMyRenderEventsTableHandle<'_> {
        SimMyRenderEventsTableHandle {
            imp: self
                .imp
                .get_table::<SimClientRenderEvent>("sim_my_render_events"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyRenderEventsInsertCallbackId(__sdk::CallbackId);
pub struct SimMyRenderEventsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyRenderEventsTableHandle<'ctx> {
    type Row = SimClientRenderEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimClientRenderEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyRenderEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderEventsInsertCallbackId {
        SimMyRenderEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyRenderEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyRenderEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderEventsDeleteCallbackId {
        SimMyRenderEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyRenderEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimClientRenderEvent>("sim_my_render_events");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimClientRenderEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimClientRenderEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimClientRenderEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_render_eventsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimClientRenderEvent`.
    fn sim_my_render_events(&self) -> __sdk::__query_builder::Table<SimClientRenderEvent>;
}

impl sim_my_render_eventsQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_render_events(&self) -> __sdk::__query_builder::Table<SimClientRenderEvent> {
        __sdk::__query_builder::Table::new("sim_my_render_events")
    }
}
