// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeEvidenceRetention {
    pub id: u64,
    pub run: String,
    pub references: u64,
}

impl __sdk::InModule for SimNativeEvidenceRetention {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeEvidenceRetention`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeEvidenceRetentionCols {
    pub id: __sdk::__query_builder::Col<SimNativeEvidenceRetention, u64>,
    pub run: __sdk::__query_builder::Col<SimNativeEvidenceRetention, String>,
    pub references: __sdk::__query_builder::Col<SimNativeEvidenceRetention, u64>,
}

impl __sdk::__query_builder::HasCols for SimNativeEvidenceRetention {
    type Cols = SimNativeEvidenceRetentionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeEvidenceRetentionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            references: __sdk::__query_builder::Col::new(table_name, "references"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeEvidenceRetention`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeEvidenceRetentionIxCols {
    pub id: __sdk::__query_builder::IxCol<SimNativeEvidenceRetention, u64>,
    pub run: __sdk::__query_builder::IxCol<SimNativeEvidenceRetention, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeEvidenceRetention {
    type IxCols = SimNativeEvidenceRetentionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeEvidenceRetentionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeEvidenceRetention {}
