// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimWorldBuildEvent {
    pub key: String,
    pub run: String,
    pub event_id: u64,
}

impl __sdk::InModule for SimWorldBuildEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimWorldBuildEvent`.
///
/// Provides typed access to columns for query building.
pub struct SimWorldBuildEventCols {
    pub key: __sdk::__query_builder::Col<SimWorldBuildEvent, String>,
    pub run: __sdk::__query_builder::Col<SimWorldBuildEvent, String>,
    pub event_id: __sdk::__query_builder::Col<SimWorldBuildEvent, u64>,
}

impl __sdk::__query_builder::HasCols for SimWorldBuildEvent {
    type Cols = SimWorldBuildEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimWorldBuildEventCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
        }
    }
}

/// Indexed column accessor struct for the table `SimWorldBuildEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimWorldBuildEventIxCols {
    pub key: __sdk::__query_builder::IxCol<SimWorldBuildEvent, String>,
}

impl __sdk::__query_builder::HasIxCols for SimWorldBuildEvent {
    type IxCols = SimWorldBuildEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimWorldBuildEventIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimWorldBuildEvent {}
