// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimWorldUpload {
    pub run: String,
    pub owner: __sdk::Identity,
    pub mode: String,
    pub total_bytes: u32,
    pub sha_256: String,
    pub received_bytes: u32,
    pub next_index: u32,
}

impl __sdk::InModule for SimWorldUpload {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimWorldUpload`.
///
/// Provides typed access to columns for query building.
pub struct SimWorldUploadCols {
    pub run: __sdk::__query_builder::Col<SimWorldUpload, String>,
    pub owner: __sdk::__query_builder::Col<SimWorldUpload, __sdk::Identity>,
    pub mode: __sdk::__query_builder::Col<SimWorldUpload, String>,
    pub total_bytes: __sdk::__query_builder::Col<SimWorldUpload, u32>,
    pub sha_256: __sdk::__query_builder::Col<SimWorldUpload, String>,
    pub received_bytes: __sdk::__query_builder::Col<SimWorldUpload, u32>,
    pub next_index: __sdk::__query_builder::Col<SimWorldUpload, u32>,
}

impl __sdk::__query_builder::HasCols for SimWorldUpload {
    type Cols = SimWorldUploadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimWorldUploadCols {
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            mode: __sdk::__query_builder::Col::new(table_name, "mode"),
            total_bytes: __sdk::__query_builder::Col::new(table_name, "total_bytes"),
            sha_256: __sdk::__query_builder::Col::new(table_name, "sha_256"),
            received_bytes: __sdk::__query_builder::Col::new(table_name, "received_bytes"),
            next_index: __sdk::__query_builder::Col::new(table_name, "next_index"),
        }
    }
}

/// Indexed column accessor struct for the table `SimWorldUpload`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimWorldUploadIxCols {
    pub owner: __sdk::__query_builder::IxCol<SimWorldUpload, __sdk::Identity>,
    pub run: __sdk::__query_builder::IxCol<SimWorldUpload, String>,
}

impl __sdk::__query_builder::HasIxCols for SimWorldUpload {
    type IxCols = SimWorldUploadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimWorldUploadIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimWorldUpload {}
