// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeClockActor {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub due_ms: u64,
    pub active: bool,
}

impl __sdk::InModule for SimNativeClockActor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeClockActor`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeClockActorCols {
    pub key: __sdk::__query_builder::Col<SimNativeClockActor, String>,
    pub run: __sdk::__query_builder::Col<SimNativeClockActor, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeClockActor, u32>,
    pub due_ms: __sdk::__query_builder::Col<SimNativeClockActor, u64>,
    pub active: __sdk::__query_builder::Col<SimNativeClockActor, bool>,
}

impl __sdk::__query_builder::HasCols for SimNativeClockActor {
    type Cols = SimNativeClockActorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeClockActorCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            due_ms: __sdk::__query_builder::Col::new(table_name, "due_ms"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeClockActor`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeClockActorIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeClockActor, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeClockActor {
    type IxCols = SimNativeClockActorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeClockActorIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeClockActor {}
