// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sim_native_paged_trace_entry_type::SimNativePagedTraceEntry;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeTracePage {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub first: u64,
    pub entries: Vec<SimNativePagedTraceEntry>,
}

impl __sdk::InModule for SimNativeTracePage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeTracePage`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeTracePageCols {
    pub key: __sdk::__query_builder::Col<SimNativeTracePage, String>,
    pub run: __sdk::__query_builder::Col<SimNativeTracePage, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeTracePage, u32>,
    pub first: __sdk::__query_builder::Col<SimNativeTracePage, u64>,
    pub entries: __sdk::__query_builder::Col<SimNativeTracePage, Vec<SimNativePagedTraceEntry>>,
}

impl __sdk::__query_builder::HasCols for SimNativeTracePage {
    type Cols = SimNativeTracePageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeTracePageCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            first: __sdk::__query_builder::Col::new(table_name, "first"),
            entries: __sdk::__query_builder::Col::new(table_name, "entries"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeTracePage`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeTracePageIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeTracePage, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeTracePage {
    type IxCols = SimNativeTracePageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeTracePageIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeTracePage {}
