// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimRun {
    pub id: String,
    pub owner: __sdk::Identity,
    pub state: String,
}

impl __sdk::InModule for SimRun {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimRun`.
///
/// Provides typed access to columns for query building.
pub struct SimRunCols {
    pub id: __sdk::__query_builder::Col<SimRun, String>,
    pub owner: __sdk::__query_builder::Col<SimRun, __sdk::Identity>,
    pub state: __sdk::__query_builder::Col<SimRun, String>,
}

impl __sdk::__query_builder::HasCols for SimRun {
    type Cols = SimRunCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimRunCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
        }
    }
}

/// Indexed column accessor struct for the table `SimRun`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimRunIxCols {
    pub id: __sdk::__query_builder::IxCol<SimRun, String>,
}

impl __sdk::__query_builder::HasIxCols for SimRun {
    type IxCols = SimRunIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimRunIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimRun {}
