// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimControllerFrameState {
    pub key: String,
    pub frame: String,
}

impl __sdk::InModule for SimControllerFrameState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimControllerFrameState`.
///
/// Provides typed access to columns for query building.
pub struct SimControllerFrameStateCols {
    pub key: __sdk::__query_builder::Col<SimControllerFrameState, String>,
    pub frame: __sdk::__query_builder::Col<SimControllerFrameState, String>,
}

impl __sdk::__query_builder::HasCols for SimControllerFrameState {
    type Cols = SimControllerFrameStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimControllerFrameStateCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            frame: __sdk::__query_builder::Col::new(table_name, "frame"),
        }
    }
}

/// Indexed column accessor struct for the table `SimControllerFrameState`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimControllerFrameStateIxCols {
    pub key: __sdk::__query_builder::IxCol<SimControllerFrameState, String>,
}

impl __sdk::__query_builder::HasIxCols for SimControllerFrameState {
    type IxCols = SimControllerFrameStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimControllerFrameStateIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimControllerFrameState {}
