// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_native_experience_type::SimNativeExperience;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_controller_experiences`.
///
/// Obtain a handle from the [`SimMyControllerExperiencesTableAccess::sim_my_controller_experiences`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_controller_experiences()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_controller_experiences().on_insert(...)`.
pub struct SimMyControllerExperiencesTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimNativeExperience>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_controller_experiences`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyControllerExperiencesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyControllerExperiencesTableHandle`], which mediates access to the table `sim_my_controller_experiences`.
    fn sim_my_controller_experiences(&self) -> SimMyControllerExperiencesTableHandle<'_>;
}

impl SimMyControllerExperiencesTableAccess for super::RemoteTables {
    fn sim_my_controller_experiences(&self) -> SimMyControllerExperiencesTableHandle<'_> {
        SimMyControllerExperiencesTableHandle {
            imp: self
                .imp
                .get_table::<SimNativeExperience>("sim_my_controller_experiences"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyControllerExperiencesInsertCallbackId(__sdk::CallbackId);
pub struct SimMyControllerExperiencesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyControllerExperiencesTableHandle<'ctx> {
    type Row = SimNativeExperience;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimNativeExperience> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyControllerExperiencesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyControllerExperiencesInsertCallbackId {
        SimMyControllerExperiencesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyControllerExperiencesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyControllerExperiencesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyControllerExperiencesDeleteCallbackId {
        SimMyControllerExperiencesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyControllerExperiencesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<SimNativeExperience>("sim_my_controller_experiences");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimNativeExperience>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimNativeExperience>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimNativeExperience`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_controller_experiencesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimNativeExperience`.
    fn sim_my_controller_experiences(&self) -> __sdk::__query_builder::Table<SimNativeExperience>;
}

impl sim_my_controller_experiencesQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_controller_experiences(&self) -> __sdk::__query_builder::Table<SimNativeExperience> {
        __sdk::__query_builder::Table::new("sim_my_controller_experiences")
    }
}
