// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeControllerCatalog {
    pub key: String,
    pub run: String,
    pub references: u64,
    pub body: String,
}

impl __sdk::InModule for SimNativeControllerCatalog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeControllerCatalog`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeControllerCatalogCols {
    pub key: __sdk::__query_builder::Col<SimNativeControllerCatalog, String>,
    pub run: __sdk::__query_builder::Col<SimNativeControllerCatalog, String>,
    pub references: __sdk::__query_builder::Col<SimNativeControllerCatalog, u64>,
    pub body: __sdk::__query_builder::Col<SimNativeControllerCatalog, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeControllerCatalog {
    type Cols = SimNativeControllerCatalogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeControllerCatalogCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            references: __sdk::__query_builder::Col::new(table_name, "references"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeControllerCatalog`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeControllerCatalogIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeControllerCatalog, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeControllerCatalog, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeControllerCatalog {
    type IxCols = SimNativeControllerCatalogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeControllerCatalogIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeControllerCatalog {}
