// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_native_site_type::SimNativeSite;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_render_sites`.
///
/// Obtain a handle from the [`SimMyRenderSitesTableAccess::sim_my_render_sites`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_render_sites()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_render_sites().on_insert(...)`.
pub struct SimMyRenderSitesTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimNativeSite>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_render_sites`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyRenderSitesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyRenderSitesTableHandle`], which mediates access to the table `sim_my_render_sites`.
    fn sim_my_render_sites(&self) -> SimMyRenderSitesTableHandle<'_>;
}

impl SimMyRenderSitesTableAccess for super::RemoteTables {
    fn sim_my_render_sites(&self) -> SimMyRenderSitesTableHandle<'_> {
        SimMyRenderSitesTableHandle {
            imp: self.imp.get_table::<SimNativeSite>("sim_my_render_sites"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyRenderSitesInsertCallbackId(__sdk::CallbackId);
pub struct SimMyRenderSitesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyRenderSitesTableHandle<'ctx> {
    type Row = SimNativeSite;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimNativeSite> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyRenderSitesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderSitesInsertCallbackId {
        SimMyRenderSitesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyRenderSitesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyRenderSitesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyRenderSitesDeleteCallbackId {
        SimMyRenderSitesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyRenderSitesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimNativeSite>("sim_my_render_sites");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimNativeSite>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimNativeSite>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimNativeSite`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_render_sitesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimNativeSite`.
    fn sim_my_render_sites(&self) -> __sdk::__query_builder::Table<SimNativeSite>;
}

impl sim_my_render_sitesQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_render_sites(&self) -> __sdk::__query_builder::Table<SimNativeSite> {
        __sdk::__query_builder::Table::new("sim_my_render_sites")
    }
}
