// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimConfigureClockRateArgs {
    pub run: String,
    pub hz: u32,
}

impl From<SimConfigureClockRateArgs> for super::Reducer {
    fn from(args: SimConfigureClockRateArgs) -> Self {
        Self::SimConfigureClockRate {
            run: args.run,
            hz: args.hz,
        }
    }
}

impl __sdk::InModule for SimConfigureClockRateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_configure_clock_rate`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_configure_clock_rate {
    /// Request that the remote module invoke the reducer `sim_configure_clock_rate` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_configure_clock_rate:sim_configure_clock_rate_then`] to run a callback after the reducer completes.
    fn sim_configure_clock_rate(&self, run: String, hz: u32) -> __sdk::Result<()> {
        self.sim_configure_clock_rate_then(run, hz, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_configure_clock_rate` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_configure_clock_rate_then(
        &self,
        run: String,
        hz: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_configure_clock_rate for super::RemoteReducers {
    fn sim_configure_clock_rate_then(
        &self,
        run: String,
        hz: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SimConfigureClockRateArgs { run, hz }, callback)
    }
}
