// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::behavior_type_type::BehaviorType;
use super::resource_type_type::ResourceType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SkillDef {
    pub id: u64,
    pub name: String,
    pub behavior_type: BehaviorType,
    pub resource_type: ResourceType,
}

impl __sdk::InModule for SkillDef {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SkillDef`.
///
/// Provides typed access to columns for query building.
pub struct SkillDefCols {
    pub id: __sdk::__query_builder::Col<SkillDef, u64>,
    pub name: __sdk::__query_builder::Col<SkillDef, String>,
    pub behavior_type: __sdk::__query_builder::Col<SkillDef, BehaviorType>,
    pub resource_type: __sdk::__query_builder::Col<SkillDef, ResourceType>,
}

impl __sdk::__query_builder::HasCols for SkillDef {
    type Cols = SkillDefCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SkillDefCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            behavior_type: __sdk::__query_builder::Col::new(table_name, "behavior_type"),
            resource_type: __sdk::__query_builder::Col::new(table_name, "resource_type"),
        }
    }
}

/// Indexed column accessor struct for the table `SkillDef`.
///
/// Provides typed access to indexed columns for query building.
pub struct SkillDefIxCols {
    pub id: __sdk::__query_builder::IxCol<SkillDef, u64>,
}

impl __sdk::__query_builder::HasIxCols for SkillDef {
    type IxCols = SkillDefIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SkillDefIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SkillDef {}
