// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnNpcArgs {
    pub x: f32,
    pub z: f32,
}

impl From<SpawnNpcArgs> for super::Reducer {
    fn from(args: SpawnNpcArgs) -> Self {
        Self::SpawnNpc {
            x: args.x,
            z: args.z,
        }
    }
}

impl __sdk::InModule for SpawnNpcArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_npc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_npc {
    /// Request that the remote module invoke the reducer `spawn_npc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`spawn_npc:spawn_npc_then`] to run a callback after the reducer completes.
    fn spawn_npc(&self, x: f32, z: f32) -> __sdk::Result<()> {
        self.spawn_npc_then(x, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `spawn_npc` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn spawn_npc_then(
        &self,
        x: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl spawn_npc for super::RemoteReducers {
    fn spawn_npc_then(
        &self,
        x: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SpawnNpcArgs { x, z }, callback)
    }
}
