// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitNpcGoalsArgs {
    pub npc_id: u64,
    pub goals_json: String,
}

impl From<SubmitNpcGoalsArgs> for super::Reducer {
    fn from(args: SubmitNpcGoalsArgs) -> Self {
        Self::SubmitNpcGoals {
            npc_id: args.npc_id,
            goals_json: args.goals_json,
        }
    }
}

impl __sdk::InModule for SubmitNpcGoalsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_npc_goals`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_npc_goals {
    /// Request that the remote module invoke the reducer `submit_npc_goals` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_npc_goals:submit_npc_goals_then`] to run a callback after the reducer completes.
    fn submit_npc_goals(&self, npc_id: u64, goals_json: String) -> __sdk::Result<()> {
        self.submit_npc_goals_then(npc_id, goals_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_npc_goals` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_npc_goals_then(
        &self,
        npc_id: u64,
        goals_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_npc_goals for super::RemoteReducers {
    fn submit_npc_goals_then(
        &self,
        npc_id: u64,
        goals_json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SubmitNpcGoalsArgs { npc_id, goals_json }, callback)
    }
}
