// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UseTargetedSkillArgs {
    pub skill_id: u64,
    pub target_kind: String,
    pub target_npc_id: u64,
    pub target_player_hex: String,
}

impl From<UseTargetedSkillArgs> for super::Reducer {
    fn from(args: UseTargetedSkillArgs) -> Self {
        Self::UseTargetedSkill {
            skill_id: args.skill_id,
            target_kind: args.target_kind,
            target_npc_id: args.target_npc_id,
            target_player_hex: args.target_player_hex,
        }
    }
}

impl __sdk::InModule for UseTargetedSkillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `use_targeted_skill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait use_targeted_skill {
    /// Request that the remote module invoke the reducer `use_targeted_skill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`use_targeted_skill:use_targeted_skill_then`] to run a callback after the reducer completes.
    fn use_targeted_skill(
        &self,
        skill_id: u64,
        target_kind: String,
        target_npc_id: u64,
        target_player_hex: String,
    ) -> __sdk::Result<()> {
        self.use_targeted_skill_then(
            skill_id,
            target_kind,
            target_npc_id,
            target_player_hex,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `use_targeted_skill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn use_targeted_skill_then(
        &self,
        skill_id: u64,
        target_kind: String,
        target_npc_id: u64,
        target_player_hex: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl use_targeted_skill for super::RemoteReducers {
    fn use_targeted_skill_then(
        &self,
        skill_id: u64,
        target_kind: String,
        target_npc_id: u64,
        target_player_hex: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UseTargetedSkillArgs {
                skill_id,
                target_kind,
                target_npc_id,
                target_player_hex,
            },
            callback,
        )
    }
}
