// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActiveSkill {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub player_identity: __sdk::Identity,
    pub skill_id: u64,
    pub started_at: u64,
    pub target_x: f32,
    pub target_y: f32,
    pub target_z: f32,
    pub dir_x: f32,
    pub dir_z: f32,
}

impl __sdk::InModule for ActiveSkill {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActiveSkill`.
///
/// Provides typed access to columns for query building.
pub struct ActiveSkillCols {
    pub scheduled_id: __sdk::__query_builder::Col<ActiveSkill, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<ActiveSkill, __sdk::ScheduleAt>,
    pub player_identity: __sdk::__query_builder::Col<ActiveSkill, __sdk::Identity>,
    pub skill_id: __sdk::__query_builder::Col<ActiveSkill, u64>,
    pub started_at: __sdk::__query_builder::Col<ActiveSkill, u64>,
    pub target_x: __sdk::__query_builder::Col<ActiveSkill, f32>,
    pub target_y: __sdk::__query_builder::Col<ActiveSkill, f32>,
    pub target_z: __sdk::__query_builder::Col<ActiveSkill, f32>,
    pub dir_x: __sdk::__query_builder::Col<ActiveSkill, f32>,
    pub dir_z: __sdk::__query_builder::Col<ActiveSkill, f32>,
}

impl __sdk::__query_builder::HasCols for ActiveSkill {
    type Cols = ActiveSkillCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActiveSkillCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            player_identity: __sdk::__query_builder::Col::new(table_name, "player_identity"),
            skill_id: __sdk::__query_builder::Col::new(table_name, "skill_id"),
            started_at: __sdk::__query_builder::Col::new(table_name, "started_at"),
            target_x: __sdk::__query_builder::Col::new(table_name, "target_x"),
            target_y: __sdk::__query_builder::Col::new(table_name, "target_y"),
            target_z: __sdk::__query_builder::Col::new(table_name, "target_z"),
            dir_x: __sdk::__query_builder::Col::new(table_name, "dir_x"),
            dir_z: __sdk::__query_builder::Col::new(table_name, "dir_z"),
        }
    }
}

/// Indexed column accessor struct for the table `ActiveSkill`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActiveSkillIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<ActiveSkill, u64>,
}

impl __sdk::__query_builder::HasIxCols for ActiveSkill {
    type IxCols = ActiveSkillIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActiveSkillIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActiveSkill {}
