// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AllocateSkillPointArgs {
    pub skill_id: u64,
    pub attribute: String,
}

impl From<AllocateSkillPointArgs> for super::Reducer {
    fn from(args: AllocateSkillPointArgs) -> Self {
        Self::AllocateSkillPoint {
            skill_id: args.skill_id,
            attribute: args.attribute,
        }
    }
}

impl __sdk::InModule for AllocateSkillPointArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `allocate_skill_point`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait allocate_skill_point {
    /// Request that the remote module invoke the reducer `allocate_skill_point` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`allocate_skill_point:allocate_skill_point_then`] to run a callback after the reducer completes.
    fn allocate_skill_point(&self, skill_id: u64, attribute: String) -> __sdk::Result<()> {
        self.allocate_skill_point_then(skill_id, attribute, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `allocate_skill_point` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn allocate_skill_point_then(
        &self,
        skill_id: u64,
        attribute: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl allocate_skill_point for super::RemoteReducers {
    fn allocate_skill_point_then(
        &self,
        skill_id: u64,
        attribute: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AllocateSkillPointArgs {
                skill_id,
                attribute,
            },
            callback,
        )
    }
}
