// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::position_type::Position;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct GroundItem {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub item_def_id: u64,
    pub quantity: i32,
    pub position: Position,
    pub owner: __sdk::Identity,
    pub free_for_all_at: u64,
}

impl __sdk::InModule for GroundItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `GroundItem`.
///
/// Provides typed access to columns for query building.
pub struct GroundItemCols {
    pub scheduled_id: __sdk::__query_builder::Col<GroundItem, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<GroundItem, __sdk::ScheduleAt>,
    pub item_def_id: __sdk::__query_builder::Col<GroundItem, u64>,
    pub quantity: __sdk::__query_builder::Col<GroundItem, i32>,
    pub position: __sdk::__query_builder::Col<GroundItem, Position>,
    pub owner: __sdk::__query_builder::Col<GroundItem, __sdk::Identity>,
    pub free_for_all_at: __sdk::__query_builder::Col<GroundItem, u64>,
}

impl __sdk::__query_builder::HasCols for GroundItem {
    type Cols = GroundItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        GroundItemCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            item_def_id: __sdk::__query_builder::Col::new(table_name, "item_def_id"),
            quantity: __sdk::__query_builder::Col::new(table_name, "quantity"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            free_for_all_at: __sdk::__query_builder::Col::new(table_name, "free_for_all_at"),
        }
    }
}

/// Indexed column accessor struct for the table `GroundItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct GroundItemIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<GroundItem, u64>,
}

impl __sdk::__query_builder::HasIxCols for GroundItem {
    type IxCols = GroundItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        GroundItemIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for GroundItem {}
