// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LootTableEntry {
    pub id: u64,
    pub item_def_id: u64,
    pub min_npc_level: i32,
    pub max_npc_level: i32,
    pub weight: i32,
    pub min_quantity: i32,
    pub max_quantity: i32,
}

impl __sdk::InModule for LootTableEntry {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `LootTableEntry`.
///
/// Provides typed access to columns for query building.
pub struct LootTableEntryCols {
    pub id: __sdk::__query_builder::Col<LootTableEntry, u64>,
    pub item_def_id: __sdk::__query_builder::Col<LootTableEntry, u64>,
    pub min_npc_level: __sdk::__query_builder::Col<LootTableEntry, i32>,
    pub max_npc_level: __sdk::__query_builder::Col<LootTableEntry, i32>,
    pub weight: __sdk::__query_builder::Col<LootTableEntry, i32>,
    pub min_quantity: __sdk::__query_builder::Col<LootTableEntry, i32>,
    pub max_quantity: __sdk::__query_builder::Col<LootTableEntry, i32>,
}

impl __sdk::__query_builder::HasCols for LootTableEntry {
    type Cols = LootTableEntryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LootTableEntryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            item_def_id: __sdk::__query_builder::Col::new(table_name, "item_def_id"),
            min_npc_level: __sdk::__query_builder::Col::new(table_name, "min_npc_level"),
            max_npc_level: __sdk::__query_builder::Col::new(table_name, "max_npc_level"),
            weight: __sdk::__query_builder::Col::new(table_name, "weight"),
            min_quantity: __sdk::__query_builder::Col::new(table_name, "min_quantity"),
            max_quantity: __sdk::__query_builder::Col::new(table_name, "max_quantity"),
        }
    }
}

/// Indexed column accessor struct for the table `LootTableEntry`.
///
/// Provides typed access to indexed columns for query building.
pub struct LootTableEntryIxCols {
    pub id: __sdk::__query_builder::IxCol<LootTableEntry, u64>,
}

impl __sdk::__query_builder::HasIxCols for LootTableEntry {
    type IxCols = LootTableEntryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LootTableEntryIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for LootTableEntry {}
