// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::equip_slot_type::EquipSlot;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcEquippedItem {
    pub id: u64,
    pub npc_id: u64,
    pub equip_slot: EquipSlot,
    pub item_def_id: u64,
    pub durability: i32,
}

impl __sdk::InModule for NpcEquippedItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `NpcEquippedItem`.
///
/// Provides typed access to columns for query building.
pub struct NpcEquippedItemCols {
    pub id: __sdk::__query_builder::Col<NpcEquippedItem, u64>,
    pub npc_id: __sdk::__query_builder::Col<NpcEquippedItem, u64>,
    pub equip_slot: __sdk::__query_builder::Col<NpcEquippedItem, EquipSlot>,
    pub item_def_id: __sdk::__query_builder::Col<NpcEquippedItem, u64>,
    pub durability: __sdk::__query_builder::Col<NpcEquippedItem, i32>,
}

impl __sdk::__query_builder::HasCols for NpcEquippedItem {
    type Cols = NpcEquippedItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcEquippedItemCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            npc_id: __sdk::__query_builder::Col::new(table_name, "npc_id"),
            equip_slot: __sdk::__query_builder::Col::new(table_name, "equip_slot"),
            item_def_id: __sdk::__query_builder::Col::new(table_name, "item_def_id"),
            durability: __sdk::__query_builder::Col::new(table_name, "durability"),
        }
    }
}

/// Indexed column accessor struct for the table `NpcEquippedItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcEquippedItemIxCols {
    pub id: __sdk::__query_builder::IxCol<NpcEquippedItem, u64>,
}

impl __sdk::__query_builder::HasIxCols for NpcEquippedItem {
    type IxCols = NpcEquippedItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcEquippedItemIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for NpcEquippedItem {}
