// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeParticipant {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub control_epoch: u64,
    pub learning_revision: u64,
    pub cursor: u64,
    pub experiences: String,
    pub speech: String,
    pub last_speech_tick: Option<u64>,
    pub learned_sources: Vec<u64>,
    pub activity: String,
    pub activity_position: Option<i32>,
}

impl __sdk::InModule for SimNativeParticipant {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeParticipant`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeParticipantCols {
    pub key: __sdk::__query_builder::Col<SimNativeParticipant, String>,
    pub run: __sdk::__query_builder::Col<SimNativeParticipant, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeParticipant, u32>,
    pub control_epoch: __sdk::__query_builder::Col<SimNativeParticipant, u64>,
    pub learning_revision: __sdk::__query_builder::Col<SimNativeParticipant, u64>,
    pub cursor: __sdk::__query_builder::Col<SimNativeParticipant, u64>,
    pub experiences: __sdk::__query_builder::Col<SimNativeParticipant, String>,
    pub speech: __sdk::__query_builder::Col<SimNativeParticipant, String>,
    pub last_speech_tick: __sdk::__query_builder::Col<SimNativeParticipant, Option<u64>>,
    pub learned_sources: __sdk::__query_builder::Col<SimNativeParticipant, Vec<u64>>,
    pub activity: __sdk::__query_builder::Col<SimNativeParticipant, String>,
    pub activity_position: __sdk::__query_builder::Col<SimNativeParticipant, Option<i32>>,
}

impl __sdk::__query_builder::HasCols for SimNativeParticipant {
    type Cols = SimNativeParticipantCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeParticipantCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            control_epoch: __sdk::__query_builder::Col::new(table_name, "control_epoch"),
            learning_revision: __sdk::__query_builder::Col::new(table_name, "learning_revision"),
            cursor: __sdk::__query_builder::Col::new(table_name, "cursor"),
            experiences: __sdk::__query_builder::Col::new(table_name, "experiences"),
            speech: __sdk::__query_builder::Col::new(table_name, "speech"),
            last_speech_tick: __sdk::__query_builder::Col::new(table_name, "last_speech_tick"),
            learned_sources: __sdk::__query_builder::Col::new(table_name, "learned_sources"),
            activity: __sdk::__query_builder::Col::new(table_name, "activity"),
            activity_position: __sdk::__query_builder::Col::new(table_name, "activity_position"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeParticipant`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeParticipantIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeParticipant, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeParticipant, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeParticipant {
    type IxCols = SimNativeParticipantIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeParticipantIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeParticipant {}
