// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SimParticipantCommandArgs {
    pub request: String,
}

impl From<SimParticipantCommandArgs> for super::Reducer {
    fn from(args: SimParticipantCommandArgs) -> Self {
        Self::SimParticipantCommand {
            request: args.request,
        }
    }
}

impl __sdk::InModule for SimParticipantCommandArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sim_participant_command`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sim_participant_command {
    /// Request that the remote module invoke the reducer `sim_participant_command` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sim_participant_command:sim_participant_command_then`] to run a callback after the reducer completes.
    fn sim_participant_command(&self, request: String) -> __sdk::Result<()> {
        self.sim_participant_command_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `sim_participant_command` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sim_participant_command_then(
        &self,
        request: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sim_participant_command for super::RemoteReducers {
    fn sim_participant_command_then(
        &self,
        request: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SimParticipantCommandArgs { request }, callback)
    }
}
