// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeActorAux {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub arena: Option<String>,
    pub lifecycle: Option<String>,
    pub offer: Option<String>,
    pub body: Option<String>,
    pub materials: Option<String>,
    pub needs_remainder_ms: Option<u64>,
    pub hazard_remainder_ms: Option<u64>,
    pub action_ready_ms: Option<u64>,
    pub dialogue_ready_ms: Option<u64>,
    pub dirty: Option<bool>,
}

impl __sdk::InModule for SimNativeActorAux {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeActorAux`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeActorAuxCols {
    pub key: __sdk::__query_builder::Col<SimNativeActorAux, String>,
    pub run: __sdk::__query_builder::Col<SimNativeActorAux, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeActorAux, u32>,
    pub arena: __sdk::__query_builder::Col<SimNativeActorAux, Option<String>>,
    pub lifecycle: __sdk::__query_builder::Col<SimNativeActorAux, Option<String>>,
    pub offer: __sdk::__query_builder::Col<SimNativeActorAux, Option<String>>,
    pub body: __sdk::__query_builder::Col<SimNativeActorAux, Option<String>>,
    pub materials: __sdk::__query_builder::Col<SimNativeActorAux, Option<String>>,
    pub needs_remainder_ms: __sdk::__query_builder::Col<SimNativeActorAux, Option<u64>>,
    pub hazard_remainder_ms: __sdk::__query_builder::Col<SimNativeActorAux, Option<u64>>,
    pub action_ready_ms: __sdk::__query_builder::Col<SimNativeActorAux, Option<u64>>,
    pub dialogue_ready_ms: __sdk::__query_builder::Col<SimNativeActorAux, Option<u64>>,
    pub dirty: __sdk::__query_builder::Col<SimNativeActorAux, Option<bool>>,
}

impl __sdk::__query_builder::HasCols for SimNativeActorAux {
    type Cols = SimNativeActorAuxCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeActorAuxCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            arena: __sdk::__query_builder::Col::new(table_name, "arena"),
            lifecycle: __sdk::__query_builder::Col::new(table_name, "lifecycle"),
            offer: __sdk::__query_builder::Col::new(table_name, "offer"),
            body: __sdk::__query_builder::Col::new(table_name, "body"),
            materials: __sdk::__query_builder::Col::new(table_name, "materials"),
            needs_remainder_ms: __sdk::__query_builder::Col::new(table_name, "needs_remainder_ms"),
            hazard_remainder_ms: __sdk::__query_builder::Col::new(
                table_name,
                "hazard_remainder_ms",
            ),
            action_ready_ms: __sdk::__query_builder::Col::new(table_name, "action_ready_ms"),
            dialogue_ready_ms: __sdk::__query_builder::Col::new(table_name, "dialogue_ready_ms"),
            dirty: __sdk::__query_builder::Col::new(table_name, "dirty"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeActorAux`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeActorAuxIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeActorAux, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeActorAux, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeActorAux {
    type IxCols = SimNativeActorAuxIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeActorAuxIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeActorAux {}
