// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimClientClock {
    pub id: u64,
    pub run: String,
    pub scheduled_at: __sdk::ScheduleAt,
    pub paused: bool,
    pub evidence_mode: String,
}

impl __sdk::InModule for SimClientClock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimClientClock`.
///
/// Provides typed access to columns for query building.
pub struct SimClientClockCols {
    pub id: __sdk::__query_builder::Col<SimClientClock, u64>,
    pub run: __sdk::__query_builder::Col<SimClientClock, String>,
    pub scheduled_at: __sdk::__query_builder::Col<SimClientClock, __sdk::ScheduleAt>,
    pub paused: __sdk::__query_builder::Col<SimClientClock, bool>,
    pub evidence_mode: __sdk::__query_builder::Col<SimClientClock, String>,
}

impl __sdk::__query_builder::HasCols for SimClientClock {
    type Cols = SimClientClockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimClientClockCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            paused: __sdk::__query_builder::Col::new(table_name, "paused"),
            evidence_mode: __sdk::__query_builder::Col::new(table_name, "evidence_mode"),
        }
    }
}

/// Indexed column accessor struct for the table `SimClientClock`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimClientClockIxCols {
    pub id: __sdk::__query_builder::IxCol<SimClientClock, u64>,
    pub run: __sdk::__query_builder::IxCol<SimClientClock, String>,
}

impl __sdk::__query_builder::HasIxCols for SimClientClock {
    type IxCols = SimClientClockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimClientClockIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimClientClock {}
