// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeMind {
    pub key: String,
    pub run: String,
    pub actor: u32,
    pub motive: String,
    pub role: String,
    pub current_goal: Option<String>,
    pub caution: i32,
    pub empathy: i32,
    pub introspection: i32,
    pub fear: i32,
    pub generation: u64,
    pub failures: u32,
    pub last_reflection: u64,
    pub last_cause: Option<u64>,
    pub execution: String,
    pub beliefs: String,
    pub relationships: String,
    pub memories: String,
    pub site_observations: String,
    pub knowledge: String,
}

impl __sdk::InModule for SimNativeMind {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeMind`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeMindCols {
    pub key: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub run: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeMind, u32>,
    pub motive: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub role: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub current_goal: __sdk::__query_builder::Col<SimNativeMind, Option<String>>,
    pub caution: __sdk::__query_builder::Col<SimNativeMind, i32>,
    pub empathy: __sdk::__query_builder::Col<SimNativeMind, i32>,
    pub introspection: __sdk::__query_builder::Col<SimNativeMind, i32>,
    pub fear: __sdk::__query_builder::Col<SimNativeMind, i32>,
    pub generation: __sdk::__query_builder::Col<SimNativeMind, u64>,
    pub failures: __sdk::__query_builder::Col<SimNativeMind, u32>,
    pub last_reflection: __sdk::__query_builder::Col<SimNativeMind, u64>,
    pub last_cause: __sdk::__query_builder::Col<SimNativeMind, Option<u64>>,
    pub execution: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub beliefs: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub relationships: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub memories: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub site_observations: __sdk::__query_builder::Col<SimNativeMind, String>,
    pub knowledge: __sdk::__query_builder::Col<SimNativeMind, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeMind {
    type Cols = SimNativeMindCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeMindCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            motive: __sdk::__query_builder::Col::new(table_name, "motive"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            current_goal: __sdk::__query_builder::Col::new(table_name, "current_goal"),
            caution: __sdk::__query_builder::Col::new(table_name, "caution"),
            empathy: __sdk::__query_builder::Col::new(table_name, "empathy"),
            introspection: __sdk::__query_builder::Col::new(table_name, "introspection"),
            fear: __sdk::__query_builder::Col::new(table_name, "fear"),
            generation: __sdk::__query_builder::Col::new(table_name, "generation"),
            failures: __sdk::__query_builder::Col::new(table_name, "failures"),
            last_reflection: __sdk::__query_builder::Col::new(table_name, "last_reflection"),
            last_cause: __sdk::__query_builder::Col::new(table_name, "last_cause"),
            execution: __sdk::__query_builder::Col::new(table_name, "execution"),
            beliefs: __sdk::__query_builder::Col::new(table_name, "beliefs"),
            relationships: __sdk::__query_builder::Col::new(table_name, "relationships"),
            memories: __sdk::__query_builder::Col::new(table_name, "memories"),
            site_observations: __sdk::__query_builder::Col::new(table_name, "site_observations"),
            knowledge: __sdk::__query_builder::Col::new(table_name, "knowledge"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeMind`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeMindIxCols {
    pub key: __sdk::__query_builder::IxCol<SimNativeMind, String>,
    pub run: __sdk::__query_builder::IxCol<SimNativeMind, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeMind {
    type IxCols = SimNativeMindIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeMindIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeMind {}
