// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeLeaseEvidence {
    pub lease_id: u64,
    pub run: String,
    pub actor: u32,
    pub experiences: String,
}

impl __sdk::InModule for SimNativeLeaseEvidence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeLeaseEvidence`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeLeaseEvidenceCols {
    pub lease_id: __sdk::__query_builder::Col<SimNativeLeaseEvidence, u64>,
    pub run: __sdk::__query_builder::Col<SimNativeLeaseEvidence, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeLeaseEvidence, u32>,
    pub experiences: __sdk::__query_builder::Col<SimNativeLeaseEvidence, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeLeaseEvidence {
    type Cols = SimNativeLeaseEvidenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeLeaseEvidenceCols {
            lease_id: __sdk::__query_builder::Col::new(table_name, "lease_id"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            experiences: __sdk::__query_builder::Col::new(table_name, "experiences"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeLeaseEvidence`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeLeaseEvidenceIxCols {
    pub lease_id: __sdk::__query_builder::IxCol<SimNativeLeaseEvidence, u64>,
    pub run: __sdk::__query_builder::IxCol<SimNativeLeaseEvidence, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeLeaseEvidence {
    type IxCols = SimNativeLeaseEvidenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeLeaseEvidenceIxCols {
            lease_id: __sdk::__query_builder::IxCol::new(table_name, "lease_id"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeLeaseEvidence {}
