// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::sim_participant_head_type::SimParticipantHead;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sim_my_participant_head`.
///
/// Obtain a handle from the [`SimMyParticipantHeadTableAccess::sim_my_participant_head`] method on [`super::RemoteTables`],
/// like `ctx.db.sim_my_participant_head()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sim_my_participant_head().on_insert(...)`.
pub struct SimMyParticipantHeadTableHandle<'ctx> {
    imp: __sdk::TableHandle<SimParticipantHead>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sim_my_participant_head`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SimMyParticipantHeadTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SimMyParticipantHeadTableHandle`], which mediates access to the table `sim_my_participant_head`.
    fn sim_my_participant_head(&self) -> SimMyParticipantHeadTableHandle<'_>;
}

impl SimMyParticipantHeadTableAccess for super::RemoteTables {
    fn sim_my_participant_head(&self) -> SimMyParticipantHeadTableHandle<'_> {
        SimMyParticipantHeadTableHandle {
            imp: self
                .imp
                .get_table::<SimParticipantHead>("sim_my_participant_head"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SimMyParticipantHeadInsertCallbackId(__sdk::CallbackId);
pub struct SimMyParticipantHeadDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SimMyParticipantHeadTableHandle<'ctx> {
    type Row = SimParticipantHead;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SimParticipantHead> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SimMyParticipantHeadInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyParticipantHeadInsertCallbackId {
        SimMyParticipantHeadInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SimMyParticipantHeadInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SimMyParticipantHeadDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SimMyParticipantHeadDeleteCallbackId {
        SimMyParticipantHeadDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SimMyParticipantHeadDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SimParticipantHead>("sim_my_participant_head");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SimParticipantHead>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SimParticipantHead>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SimParticipantHead`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sim_my_participant_headQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SimParticipantHead`.
    fn sim_my_participant_head(&self) -> __sdk::__query_builder::Table<SimParticipantHead>;
}

impl sim_my_participant_headQueryTableAccess for __sdk::QueryTableAccessor {
    fn sim_my_participant_head(&self) -> __sdk::__query_builder::Table<SimParticipantHead> {
        __sdk::__query_builder::Table::new("sim_my_participant_head")
    }
}
