// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SimNativeLease {
    pub id: u64,
    pub run: String,
    pub actor: u32,
    pub ordinal: u32,
    pub request_id: String,
    pub observed_cursor: u64,
    pub expires_ms: u64,
    pub has_observation: bool,
    pub experiences: String,
}

impl __sdk::InModule for SimNativeLease {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SimNativeLease`.
///
/// Provides typed access to columns for query building.
pub struct SimNativeLeaseCols {
    pub id: __sdk::__query_builder::Col<SimNativeLease, u64>,
    pub run: __sdk::__query_builder::Col<SimNativeLease, String>,
    pub actor: __sdk::__query_builder::Col<SimNativeLease, u32>,
    pub ordinal: __sdk::__query_builder::Col<SimNativeLease, u32>,
    pub request_id: __sdk::__query_builder::Col<SimNativeLease, String>,
    pub observed_cursor: __sdk::__query_builder::Col<SimNativeLease, u64>,
    pub expires_ms: __sdk::__query_builder::Col<SimNativeLease, u64>,
    pub has_observation: __sdk::__query_builder::Col<SimNativeLease, bool>,
    pub experiences: __sdk::__query_builder::Col<SimNativeLease, String>,
}

impl __sdk::__query_builder::HasCols for SimNativeLease {
    type Cols = SimNativeLeaseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SimNativeLeaseCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            run: __sdk::__query_builder::Col::new(table_name, "run"),
            actor: __sdk::__query_builder::Col::new(table_name, "actor"),
            ordinal: __sdk::__query_builder::Col::new(table_name, "ordinal"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            observed_cursor: __sdk::__query_builder::Col::new(table_name, "observed_cursor"),
            expires_ms: __sdk::__query_builder::Col::new(table_name, "expires_ms"),
            has_observation: __sdk::__query_builder::Col::new(table_name, "has_observation"),
            experiences: __sdk::__query_builder::Col::new(table_name, "experiences"),
        }
    }
}

/// Indexed column accessor struct for the table `SimNativeLease`.
///
/// Provides typed access to indexed columns for query building.
pub struct SimNativeLeaseIxCols {
    pub id: __sdk::__query_builder::IxCol<SimNativeLease, u64>,
    pub run: __sdk::__query_builder::IxCol<SimNativeLease, String>,
}

impl __sdk::__query_builder::HasIxCols for SimNativeLease {
    type IxCols = SimNativeLeaseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SimNativeLeaseIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            run: __sdk::__query_builder::IxCol::new(table_name, "run"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SimNativeLease {}
