// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::behavior_type_type::BehaviorType;
use super::resource_type_type::ResourceType;
use super::skill_def_type::SkillDef;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `skill_def`.
///
/// Obtain a handle from the [`SkillDefTableAccess::skill_def`] method on [`super::RemoteTables`],
/// like `ctx.db.skill_def()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_def().on_insert(...)`.
pub struct SkillDefTableHandle<'ctx> {
    imp: __sdk::TableHandle<SkillDef>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `skill_def`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SkillDefTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SkillDefTableHandle`], which mediates access to the table `skill_def`.
    fn skill_def(&self) -> SkillDefTableHandle<'_>;
}

impl SkillDefTableAccess for super::RemoteTables {
    fn skill_def(&self) -> SkillDefTableHandle<'_> {
        SkillDefTableHandle {
            imp: self.imp.get_table::<SkillDef>("skill_def"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SkillDefInsertCallbackId(__sdk::CallbackId);
pub struct SkillDefDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SkillDefTableHandle<'ctx> {
    type Row = SkillDef;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SkillDef> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SkillDefInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillDefInsertCallbackId {
        SkillDefInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SkillDefInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SkillDefDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SkillDefDeleteCallbackId {
        SkillDefDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SkillDefDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SkillDefUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SkillDefTableHandle<'ctx> {
    type UpdateCallbackId = SkillDefUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SkillDefUpdateCallbackId {
        SkillDefUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SkillDefUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `skill_def`,
/// which allows point queries on the field of the same name
/// via the [`SkillDefIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.skill_def().id().find(...)`.
pub struct SkillDefIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SkillDef, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SkillDefTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `skill_def`.
    pub fn id(&self) -> SkillDefIdUnique<'ctx> {
        SkillDefIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SkillDefIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SkillDef> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SkillDef>("skill_def");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SkillDef>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SkillDef>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SkillDef`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait skill_defQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SkillDef`.
    fn skill_def(&self) -> __sdk::__query_builder::Table<SkillDef>;
}

impl skill_defQueryTableAccess for __sdk::QueryTableAccessor {
    fn skill_def(&self) -> __sdk::__query_builder::Table<SkillDef> {
        __sdk::__query_builder::Table::new("skill_def")
    }
}
