// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitNpcReflectionArgs {
    pub npc_id: u64,
    pub json: String,
}

impl From<SubmitNpcReflectionArgs> for super::Reducer {
    fn from(args: SubmitNpcReflectionArgs) -> Self {
        Self::SubmitNpcReflection {
            npc_id: args.npc_id,
            json: args.json,
        }
    }
}

impl __sdk::InModule for SubmitNpcReflectionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_npc_reflection`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_npc_reflection {
    /// Request that the remote module invoke the reducer `submit_npc_reflection` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_npc_reflection:submit_npc_reflection_then`] to run a callback after the reducer completes.
    fn submit_npc_reflection(&self, npc_id: u64, json: String) -> __sdk::Result<()> {
        self.submit_npc_reflection_then(npc_id, json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_npc_reflection` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_npc_reflection_then(
        &self,
        npc_id: u64,
        json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_npc_reflection for super::RemoteReducers {
    fn submit_npc_reflection_then(
        &self,
        npc_id: u64,
        json: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SubmitNpcReflectionArgs { npc_id, json }, callback)
    }
}
