// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitNpcKnowledgeArgs {
    pub npc_id: u64,
    pub category: String,
    pub fact: String,
    pub learned_from: String,
    pub confidence: f32,
}

impl From<SubmitNpcKnowledgeArgs> for super::Reducer {
    fn from(args: SubmitNpcKnowledgeArgs) -> Self {
        Self::SubmitNpcKnowledge {
            npc_id: args.npc_id,
            category: args.category,
            fact: args.fact,
            learned_from: args.learned_from,
            confidence: args.confidence,
        }
    }
}

impl __sdk::InModule for SubmitNpcKnowledgeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_npc_knowledge`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_npc_knowledge {
    /// Request that the remote module invoke the reducer `submit_npc_knowledge` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_npc_knowledge:submit_npc_knowledge_then`] to run a callback after the reducer completes.
    fn submit_npc_knowledge(
        &self,
        npc_id: u64,
        category: String,
        fact: String,
        learned_from: String,
        confidence: f32,
    ) -> __sdk::Result<()> {
        self.submit_npc_knowledge_then(npc_id, category, fact, learned_from, confidence, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_npc_knowledge` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_npc_knowledge_then(
        &self,
        npc_id: u64,
        category: String,
        fact: String,
        learned_from: String,
        confidence: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_npc_knowledge for super::RemoteReducers {
    fn submit_npc_knowledge_then(
        &self,
        npc_id: u64,
        category: String,
        fact: String,
        learned_from: String,
        confidence: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SubmitNpcKnowledgeArgs {
                npc_id,
                category,
                fact,
                learned_from,
                confidence,
            },
            callback,
        )
    }
}
