// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UseItemArgs {
    pub inventory_item_id: u64,
}

impl From<UseItemArgs> for super::Reducer {
    fn from(args: UseItemArgs) -> Self {
        Self::UseItem {
            inventory_item_id: args.inventory_item_id,
        }
    }
}

impl __sdk::InModule for UseItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `use_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait use_item {
    /// Request that the remote module invoke the reducer `use_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`use_item:use_item_then`] to run a callback after the reducer completes.
    fn use_item(&self, inventory_item_id: u64) -> __sdk::Result<()> {
        self.use_item_then(inventory_item_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `use_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn use_item_then(
        &self,
        inventory_item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl use_item for super::RemoteReducers {
    fn use_item_then(
        &self,
        inventory_item_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UseItemArgs { inventory_item_id }, callback)
    }
}
