// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BrainRefreshContextArgs {
    pub context: String,
}

impl From<BrainRefreshContextArgs> for super::Reducer {
    fn from(args: BrainRefreshContextArgs) -> Self {
        Self::BrainRefreshContext {
            context: args.context,
        }
    }
}

impl __sdk::InModule for BrainRefreshContextArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `brain_refresh_context`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait brain_refresh_context {
    /// Request that the remote module invoke the reducer `brain_refresh_context` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`brain_refresh_context:brain_refresh_context_then`] to run a callback after the reducer completes.
    fn brain_refresh_context(&self, context: String) -> __sdk::Result<()> {
        self.brain_refresh_context_then(context, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `brain_refresh_context` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn brain_refresh_context_then(
        &self,
        context: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl brain_refresh_context for super::RemoteReducers {
    fn brain_refresh_context_then(
        &self,
        context: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BrainRefreshContextArgs { context }, callback)
    }
}
