// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BrainRead {
    pub key: String,
    pub owner: __sdk::Identity,
    pub sequence: u64,
    pub request_id: String,
    pub cursor: u64,
    pub expires_ms: u64,
    pub observation: String,
}

impl __sdk::InModule for BrainRead {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BrainRead`.
///
/// Provides typed access to columns for query building.
pub struct BrainReadCols {
    pub key: __sdk::__query_builder::Col<BrainRead, String>,
    pub owner: __sdk::__query_builder::Col<BrainRead, __sdk::Identity>,
    pub sequence: __sdk::__query_builder::Col<BrainRead, u64>,
    pub request_id: __sdk::__query_builder::Col<BrainRead, String>,
    pub cursor: __sdk::__query_builder::Col<BrainRead, u64>,
    pub expires_ms: __sdk::__query_builder::Col<BrainRead, u64>,
    pub observation: __sdk::__query_builder::Col<BrainRead, String>,
}

impl __sdk::__query_builder::HasCols for BrainRead {
    type Cols = BrainReadCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BrainReadCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            cursor: __sdk::__query_builder::Col::new(table_name, "cursor"),
            expires_ms: __sdk::__query_builder::Col::new(table_name, "expires_ms"),
            observation: __sdk::__query_builder::Col::new(table_name, "observation"),
        }
    }
}

/// Indexed column accessor struct for the table `BrainRead`.
///
/// Provides typed access to indexed columns for query building.
pub struct BrainReadIxCols {
    pub key: __sdk::__query_builder::IxCol<BrainRead, String>,
}

impl __sdk::__query_builder::HasIxCols for BrainRead {
    type IxCols = BrainReadIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BrainReadIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BrainRead {}
