// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BrainReceipt {
    pub key: String,
    pub owner: __sdk::Identity,
    pub sequence: u64,
    pub request_id: String,
    pub fingerprint: String,
    pub receipt: String,
}

impl __sdk::InModule for BrainReceipt {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BrainReceipt`.
///
/// Provides typed access to columns for query building.
pub struct BrainReceiptCols {
    pub key: __sdk::__query_builder::Col<BrainReceipt, String>,
    pub owner: __sdk::__query_builder::Col<BrainReceipt, __sdk::Identity>,
    pub sequence: __sdk::__query_builder::Col<BrainReceipt, u64>,
    pub request_id: __sdk::__query_builder::Col<BrainReceipt, String>,
    pub fingerprint: __sdk::__query_builder::Col<BrainReceipt, String>,
    pub receipt: __sdk::__query_builder::Col<BrainReceipt, String>,
}

impl __sdk::__query_builder::HasCols for BrainReceipt {
    type Cols = BrainReceiptCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BrainReceiptCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            request_id: __sdk::__query_builder::Col::new(table_name, "request_id"),
            fingerprint: __sdk::__query_builder::Col::new(table_name, "fingerprint"),
            receipt: __sdk::__query_builder::Col::new(table_name, "receipt"),
        }
    }
}

/// Indexed column accessor struct for the table `BrainReceipt`.
///
/// Provides typed access to indexed columns for query building.
pub struct BrainReceiptIxCols {
    pub key: __sdk::__query_builder::IxCol<BrainReceipt, String>,
}

impl __sdk::__query_builder::HasIxCols for BrainReceipt {
    type IxCols = BrainReceiptIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BrainReceiptIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BrainReceipt {}
