// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BrainJournalRetention {
    pub owner: __sdk::Identity,
    pub archived_through: u64,
    pub next_sequence: u64,
    pub plain_bytes: u64,
    pub compressed_bytes: u64,
    pub blocked: Option<String>,
}

impl __sdk::InModule for BrainJournalRetention {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BrainJournalRetention`.
///
/// Provides typed access to columns for query building.
pub struct BrainJournalRetentionCols {
    pub owner: __sdk::__query_builder::Col<BrainJournalRetention, __sdk::Identity>,
    pub archived_through: __sdk::__query_builder::Col<BrainJournalRetention, u64>,
    pub next_sequence: __sdk::__query_builder::Col<BrainJournalRetention, u64>,
    pub plain_bytes: __sdk::__query_builder::Col<BrainJournalRetention, u64>,
    pub compressed_bytes: __sdk::__query_builder::Col<BrainJournalRetention, u64>,
    pub blocked: __sdk::__query_builder::Col<BrainJournalRetention, Option<String>>,
}

impl __sdk::__query_builder::HasCols for BrainJournalRetention {
    type Cols = BrainJournalRetentionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BrainJournalRetentionCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            archived_through: __sdk::__query_builder::Col::new(table_name, "archived_through"),
            next_sequence: __sdk::__query_builder::Col::new(table_name, "next_sequence"),
            plain_bytes: __sdk::__query_builder::Col::new(table_name, "plain_bytes"),
            compressed_bytes: __sdk::__query_builder::Col::new(table_name, "compressed_bytes"),
            blocked: __sdk::__query_builder::Col::new(table_name, "blocked"),
        }
    }
}

/// Indexed column accessor struct for the table `BrainJournalRetention`.
///
/// Provides typed access to indexed columns for query building.
pub struct BrainJournalRetentionIxCols {
    pub owner: __sdk::__query_builder::IxCol<BrainJournalRetention, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for BrainJournalRetention {
    type IxCols = BrainJournalRetentionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BrainJournalRetentionIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BrainJournalRetention {}
