// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BrainJournal {
    pub key: String,
    pub owner: __sdk::Identity,
    pub sequence: u64,
    pub kind: String,
    pub data: String,
}

impl __sdk::InModule for BrainJournal {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BrainJournal`.
///
/// Provides typed access to columns for query building.
pub struct BrainJournalCols {
    pub key: __sdk::__query_builder::Col<BrainJournal, String>,
    pub owner: __sdk::__query_builder::Col<BrainJournal, __sdk::Identity>,
    pub sequence: __sdk::__query_builder::Col<BrainJournal, u64>,
    pub kind: __sdk::__query_builder::Col<BrainJournal, String>,
    pub data: __sdk::__query_builder::Col<BrainJournal, String>,
}

impl __sdk::__query_builder::HasCols for BrainJournal {
    type Cols = BrainJournalCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BrainJournalCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            sequence: __sdk::__query_builder::Col::new(table_name, "sequence"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `BrainJournal`.
///
/// Provides typed access to indexed columns for query building.
pub struct BrainJournalIxCols {
    pub key: __sdk::__query_builder::IxCol<BrainJournal, String>,
}

impl __sdk::__query_builder::HasIxCols for BrainJournal {
    type IxCols = BrainJournalIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BrainJournalIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BrainJournal {}
