// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BrainIngestArgs {
    pub frame: String,
    pub experiences: String,
    pub holdings: Option<String>,
}

impl From<BrainIngestArgs> for super::Reducer {
    fn from(args: BrainIngestArgs) -> Self {
        Self::BrainIngest {
            frame: args.frame,
            experiences: args.experiences,
            holdings: args.holdings,
        }
    }
}

impl __sdk::InModule for BrainIngestArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `brain_ingest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait brain_ingest {
    /// Request that the remote module invoke the reducer `brain_ingest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`brain_ingest:brain_ingest_then`] to run a callback after the reducer completes.
    fn brain_ingest(
        &self,
        frame: String,
        experiences: String,
        holdings: Option<String>,
    ) -> __sdk::Result<()> {
        self.brain_ingest_then(frame, experiences, holdings, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `brain_ingest` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn brain_ingest_then(
        &self,
        frame: String,
        experiences: String,
        holdings: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl brain_ingest for super::RemoteReducers {
    fn brain_ingest_then(
        &self,
        frame: String,
        experiences: String,
        holdings: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            BrainIngestArgs {
                frame,
                experiences,
                holdings,
            },
            callback,
        )
    }
}
