// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BrainJournalBlock {
    pub key: String,
    pub owner: __sdk::Identity,
    pub first: u64,
    pub last: u64,
    pub plain_bytes: u64,
    pub digest: String,
    pub zlib: Vec<u8>,
}

impl __sdk::InModule for BrainJournalBlock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BrainJournalBlock`.
///
/// Provides typed access to columns for query building.
pub struct BrainJournalBlockCols {
    pub key: __sdk::__query_builder::Col<BrainJournalBlock, String>,
    pub owner: __sdk::__query_builder::Col<BrainJournalBlock, __sdk::Identity>,
    pub first: __sdk::__query_builder::Col<BrainJournalBlock, u64>,
    pub last: __sdk::__query_builder::Col<BrainJournalBlock, u64>,
    pub plain_bytes: __sdk::__query_builder::Col<BrainJournalBlock, u64>,
    pub digest: __sdk::__query_builder::Col<BrainJournalBlock, String>,
    pub zlib: __sdk::__query_builder::Col<BrainJournalBlock, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for BrainJournalBlock {
    type Cols = BrainJournalBlockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BrainJournalBlockCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            first: __sdk::__query_builder::Col::new(table_name, "first"),
            last: __sdk::__query_builder::Col::new(table_name, "last"),
            plain_bytes: __sdk::__query_builder::Col::new(table_name, "plain_bytes"),
            digest: __sdk::__query_builder::Col::new(table_name, "digest"),
            zlib: __sdk::__query_builder::Col::new(table_name, "zlib"),
        }
    }
}

/// Indexed column accessor struct for the table `BrainJournalBlock`.
///
/// Provides typed access to indexed columns for query building.
pub struct BrainJournalBlockIxCols {
    pub key: __sdk::__query_builder::IxCol<BrainJournalBlock, String>,
}

impl __sdk::__query_builder::HasIxCols for BrainJournalBlock {
    type IxCols = BrainJournalBlockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BrainJournalBlockIxCols {
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BrainJournalBlock {}
