// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BrainAckArgs {
    pub receipt: String,
}

impl From<BrainAckArgs> for super::Reducer {
    fn from(args: BrainAckArgs) -> Self {
        Self::BrainAck {
            receipt: args.receipt,
        }
    }
}

impl __sdk::InModule for BrainAckArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `brain_ack`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait brain_ack {
    /// Request that the remote module invoke the reducer `brain_ack` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`brain_ack:brain_ack_then`] to run a callback after the reducer completes.
    fn brain_ack(&self, receipt: String) -> __sdk::Result<()> {
        self.brain_ack_then(receipt, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `brain_ack` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn brain_ack_then(
        &self,
        receipt: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl brain_ack for super::RemoteReducers {
    fn brain_ack_then(
        &self,
        receipt: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(BrainAckArgs { receipt }, callback)
    }
}
