// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BrainLastAck {
    pub owner: __sdk::Identity,
    pub receipt: String,
}

impl __sdk::InModule for BrainLastAck {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BrainLastAck`.
///
/// Provides typed access to columns for query building.
pub struct BrainLastAckCols {
    pub owner: __sdk::__query_builder::Col<BrainLastAck, __sdk::Identity>,
    pub receipt: __sdk::__query_builder::Col<BrainLastAck, String>,
}

impl __sdk::__query_builder::HasCols for BrainLastAck {
    type Cols = BrainLastAckCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BrainLastAckCols {
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            receipt: __sdk::__query_builder::Col::new(table_name, "receipt"),
        }
    }
}

/// Indexed column accessor struct for the table `BrainLastAck`.
///
/// Provides typed access to indexed columns for query building.
pub struct BrainLastAckIxCols {
    pub owner: __sdk::__query_builder::IxCol<BrainLastAck, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for BrainLastAck {
    type IxCols = BrainLastAckIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BrainLastAckIxCols {
            owner: __sdk::__query_builder::IxCol::new(table_name, "owner"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for BrainLastAck {}
