// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::brain_journal_type::BrainJournal;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_brain_journal`.
///
/// Obtain a handle from the [`MyBrainJournalTableAccess::my_brain_journal`] method on [`super::RemoteTables`],
/// like `ctx.db.my_brain_journal()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_brain_journal().on_insert(...)`.
pub struct MyBrainJournalTableHandle<'ctx> {
    imp: __sdk::TableHandle<BrainJournal>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_brain_journal`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyBrainJournalTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyBrainJournalTableHandle`], which mediates access to the table `my_brain_journal`.
    fn my_brain_journal(&self) -> MyBrainJournalTableHandle<'_>;
}

impl MyBrainJournalTableAccess for super::RemoteTables {
    fn my_brain_journal(&self) -> MyBrainJournalTableHandle<'_> {
        MyBrainJournalTableHandle {
            imp: self.imp.get_table::<BrainJournal>("my_brain_journal"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyBrainJournalInsertCallbackId(__sdk::CallbackId);
pub struct MyBrainJournalDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyBrainJournalTableHandle<'ctx> {
    type Row = BrainJournal;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BrainJournal> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyBrainJournalInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBrainJournalInsertCallbackId {
        MyBrainJournalInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyBrainJournalInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyBrainJournalDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBrainJournalDeleteCallbackId {
        MyBrainJournalDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyBrainJournalDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BrainJournal>("my_brain_journal");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BrainJournal>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BrainJournal>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BrainJournal`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_brain_journalQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BrainJournal`.
    fn my_brain_journal(&self) -> __sdk::__query_builder::Table<BrainJournal>;
}

impl my_brain_journalQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_brain_journal(&self) -> __sdk::__query_builder::Table<BrainJournal> {
        __sdk::__query_builder::Table::new("my_brain_journal")
    }
}
