// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::brain_receipt_type::BrainReceipt;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_brain_receipts`.
///
/// Obtain a handle from the [`MyBrainReceiptsTableAccess::my_brain_receipts`] method on [`super::RemoteTables`],
/// like `ctx.db.my_brain_receipts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_brain_receipts().on_insert(...)`.
pub struct MyBrainReceiptsTableHandle<'ctx> {
    imp: __sdk::TableHandle<BrainReceipt>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_brain_receipts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyBrainReceiptsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyBrainReceiptsTableHandle`], which mediates access to the table `my_brain_receipts`.
    fn my_brain_receipts(&self) -> MyBrainReceiptsTableHandle<'_>;
}

impl MyBrainReceiptsTableAccess for super::RemoteTables {
    fn my_brain_receipts(&self) -> MyBrainReceiptsTableHandle<'_> {
        MyBrainReceiptsTableHandle {
            imp: self.imp.get_table::<BrainReceipt>("my_brain_receipts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyBrainReceiptsInsertCallbackId(__sdk::CallbackId);
pub struct MyBrainReceiptsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyBrainReceiptsTableHandle<'ctx> {
    type Row = BrainReceipt;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BrainReceipt> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyBrainReceiptsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBrainReceiptsInsertCallbackId {
        MyBrainReceiptsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyBrainReceiptsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyBrainReceiptsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBrainReceiptsDeleteCallbackId {
        MyBrainReceiptsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyBrainReceiptsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BrainReceipt>("my_brain_receipts");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BrainReceipt>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BrainReceipt>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BrainReceipt`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_brain_receiptsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BrainReceipt`.
    fn my_brain_receipts(&self) -> __sdk::__query_builder::Table<BrainReceipt>;
}

impl my_brain_receiptsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_brain_receipts(&self) -> __sdk::__query_builder::Table<BrainReceipt> {
        __sdk::__query_builder::Table::new("my_brain_receipts")
    }
}
