// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::brain_outbox_type::BrainOutbox;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_brain_outbox`.
///
/// Obtain a handle from the [`MyBrainOutboxTableAccess::my_brain_outbox`] method on [`super::RemoteTables`],
/// like `ctx.db.my_brain_outbox()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_brain_outbox().on_insert(...)`.
pub struct MyBrainOutboxTableHandle<'ctx> {
    imp: __sdk::TableHandle<BrainOutbox>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_brain_outbox`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyBrainOutboxTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyBrainOutboxTableHandle`], which mediates access to the table `my_brain_outbox`.
    fn my_brain_outbox(&self) -> MyBrainOutboxTableHandle<'_>;
}

impl MyBrainOutboxTableAccess for super::RemoteTables {
    fn my_brain_outbox(&self) -> MyBrainOutboxTableHandle<'_> {
        MyBrainOutboxTableHandle {
            imp: self.imp.get_table::<BrainOutbox>("my_brain_outbox"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyBrainOutboxInsertCallbackId(__sdk::CallbackId);
pub struct MyBrainOutboxDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyBrainOutboxTableHandle<'ctx> {
    type Row = BrainOutbox;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BrainOutbox> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyBrainOutboxInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBrainOutboxInsertCallbackId {
        MyBrainOutboxInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyBrainOutboxInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyBrainOutboxDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyBrainOutboxDeleteCallbackId {
        MyBrainOutboxDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyBrainOutboxDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BrainOutbox>("my_brain_outbox");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<BrainOutbox>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BrainOutbox>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `BrainOutbox`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_brain_outboxQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `BrainOutbox`.
    fn my_brain_outbox(&self) -> __sdk::__query_builder::Table<BrainOutbox>;
}

impl my_brain_outboxQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_brain_outbox(&self) -> __sdk::__query_builder::Table<BrainOutbox> {
        __sdk::__query_builder::Table::new("my_brain_outbox")
    }
}
